# Texas Licenses

We originall got our dataset from the [License Files page](https://www.license.state.tx.us/licensesearch/licfile.asp) from the Texas Department of Licensing and Regulation, but they've changed around since then! I'm pretty sure it's [this dataset](https://www.opendatanetwork.com/dataset/data.texas.gov/7358-krk7), but we'll just use a local version instead of the most current.

# PART ONE: OPENING UP OUR DATASET

## 0. Do your setup

Import what you need to import, etc.

In [1]:
import pandas as pd
%matplotlib inline

import re

import numpy as np

%matplotlib inline

df= pd.read_csv("licfile.csv")

C:\Users\Shaleen\AppData\Local\Programs\Python\Python37-32\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (1,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

## 1. Open the file

We'll start with `licfile.csv`, which is a list of licenses.

In [2]:
df

,Associate Auctioneer,7326,ANGELINA,"RISINGER, JIM MARVIN",Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,08102017,"RISINGER, JIM MARVIN.1",7668 S US HWY 59,Unnamed: 11,NACOGDOCHES TX 75964,0347,NACOGDOCHES,75964,9363665745,Unnamed: 17,N
0,Associate Auctioneer,7962,UPSHUR,"WILLIAMS, JON ANDRE",NaN,NaN,NaN,NaN,12292017,"WILLIAMS, JON ANDRE",228 FM 1252,NaN,KILGORE TX 75662,183.0,GREGG,75662,9039187899,NaN,N
1,Associate Auctioneer,8406,WILSON,"GUEVARA, JUAN ANTONIO",NaN,NaN,NaN,NaN,9262017,"GUEVARA, JUAN ANTONIO",6909 HWY 181,NaN,POTH TX 78147,493.0,WILSON,78147,NaN,NaN,N
2,Associate Auctioneer,10543,HARRIS,"BOWERS, JAMES BRISCOE II",NaN,NaN,NaN,NaN,11042017,"BOWERS, JAMES BRISCOE II",6767 NORTH FWY,NaN,HOUSTON TX 77076-2027,201.0,HARRIS,77076,7136445566,NaN,N
3,Associate Auctioneer,10642,BELL,"DEMSKY, JOHN EDWARD",NaN,NaN,NaN,NaN,2252018,"DEMSKY, JOHN EDWARD",130 E CLARK ST,NaN,BARTLETT TX 76511,27.0,BELL,76511,2549852228,NaN,N
4,Associate Auctioneer,15650,OUT OF STATE,"THOMPSON, RANDY D",NaN,NaN,NaN,NaN,5042017,"THOMPSON, RANDY D",10995 BELLEVILLE RD,NaN,RINGLING OK 73456,999.0,OUT OF STATE,73456,5802765961,NaN,N
5,Associate Auctioneer,15698,OUT OF STATE,"TUCKER, MONTE EARL",NaN,NaN,NaN,NaN,6162017,"TUCKER, MONTE EARL",19139 HIGHWAY 6,NaN,SAYRE OK 73662-6080,999.0,OUT OF STATE,73662,5802250269,NaN,N
6,Associate Auctioneer,15810,MILAM,"COOPER, THOMAS JAMES",NaN,NaN,NaN,NaN,3182017,"COOPER, THOMAS JAMES",346 MAIN ST,NaN,ROSEBUD TX 76570,145.0,FALLS,76570,2815078713,NaN,N
7,Associate Auctioneer,15835,OUT OF STATE,"BLANKENSHIP, KERRY NEIL",NaN,NaN,NaN,NaN,5042017,"BLANKENSHIP, KERRY NEIL",10664 BELLEVILLE RD,NaN,RINGLING OK 73456-2014,999.0,OUT OF STATE,73456,5802765961,NaN,N
8,Associate Auctioneer,16784,OUT OF STATE,"DAWES, NICHOLAS MORGAN",NaN,NaN,NaN,NaN,10192017,"DAWES, NICHOLAS MORGAN",3500 MAPLE AVENUE 17TH FLOOR,NaN,DALLAS TX 75219,113.0,DALLAS,75219,2144091137,NaN,N
9,Associate Auctioneer,16893,LAMAR,"LESTER, TIMMY EUGENE",NaN,NaN,NaN,NaN,8192017,"LESTER, TIMMY EUGENE",167 COUNTY ROAD 16380,NaN,CUNNINGHAM TX 75434,277.0,LAMAR,75434,9037825759,NaN,N
10,Associate Auctioneer,16969,NACOGDOCHES,"MANCILL, MARK DUANE",NaN,NaN,NaN,NaN,4212017,"MANCILL, MARK DUANE",116 TRAILWOOD CIR,NaN,LUFKIN TX 75904-4331,5.0,ANGELINA,75904,9366749636,NaN,N
11,Associate Auctioneer,16990,BEXAR,"HUDDLESTON, SHAWN ALAN",NaN,NaN,NaN,NaN,2182017,"HUDDLESTON, SHAWN ALAN",3903 EISENHOUER RD,NaN,SAN ANTONIO TX 78218,29.0,BEXAR,78218,2106815425,NaN,N
12,Associate Auctioneer,17072,ECTOR,"JORDAN, JAMES EUGENE",NaN,NaN,NaN,NaN,2182018,"JORDAN, JAMES EUGENE",6190 CARGO RD,NaN,ODESSA TX 79762,135.0,ECTOR,79762,4322722266,NaN,N
13,Associate Auctioneer,17108,KAUFMAN,"IRWIN, MICHAEL RICHARD",NaN,NaN,NaN,NaN,2252017,"IRWIN, MICHAEL RICHARD",8513 MICHAEL TALTY AVE,NaN,TERRELL TX 75160-7592,257.0,KAUFMAN,75160,4695951384,NaN,N
14,Associate Auctioneer,17241,HOOD,"HALL, WESLEY RYON",NaN,NaN,NaN,NaN,1252018,"HALL, WESLEY RYON",13016 HWY 36,NaN,COMANCHE TX 76442-7305,93.0,COMANCHE,76442,3253565950,NaN,N
15,Associate Auctioneer,17242,ERATH,"JAMES, BACHUS ROSS",NaN,NaN,NaN,NaN,5042017,"JAMES, BACHUS ROSS",471 N HARBIN DR,NaN,STEPHENVILLE TX 76401-2860,143.0,ERATH,76401,2545928394,NaN,N
16,Associate Auctioneer,17669,JOHNSON,"SIDAWI, JOSEPH JAMES",NaN,NaN,NaN,NaN,2082017,"SIDAWI, JOSEPH JAMES",2032 W FM 917,NaN,JOSHUA TX 76058-6060,251.0,JOHNSON,76058,8173200833,NaN,N
17,Associate Auctioneer,17671,MILLS,"SMITH, DAVID JAMES",NaN,NaN,NaN,NaN,2082018,"SMITH, DAVID JAMES",1110 US HIGHWAY 84 WEST,NaN,GOLDTHWAITE TX 76844,333.0,MILLS,76844,3259386750,NaN,N
18,Associate Auctioneer,17672,BROWN,"FERGUSON, JACKIE LEE",NaN,NaN,NaN,NaN,2092018,"FERGUSON, JACKIE LEE",119 E KYLE ST,NaN,BANGS TX 76823,49.0,BROWN,76823,3253727333,NaN,N
19,Associate Auctioneer,17675,UPSHUR,"MCKINLEY, MATTHEW D",NaN,NaN,NaN,NaN,2182018,"MCKINLEY, MATTHEW D",805 BROADWAY AVE,NaN,GLADEWATER TX 75647-2415,183.0,GREGG,75647,9038453830,NaN,N
20,Associate Auctioneer,17676,JOHNSON,"SOWELL, KALEN BRICE",NaN,NaN,NaN,NaN,2182018,"SOWELL, KALEN BRICE",111 N BROADWAY ST,NaN,CRESSON TX 76035,221.0,HOOD,76035,8173821530,NaN,N
21,Associate Auctioneer,17679,ELLIS,"SEVIER, VIRGINIA A",NaN,NaN,NaN,NaN,2252018,"SEVIER, VIRGINIA A",212 S ROGERS,NaN,WAXAHACHIE TX 75165,139.0,ELLIS,75165,9726930572,NaN,N
22,Associate Auctioneer,17680,BELL,"SOMERVILLE, CAL W",NaN,NaN,NaN,NaN,2252017,"SOMERVILLE, CAL W",202 BRANDY LOOP,NaN,KILLEEN TX 76549-9049,27.0,BELL,76549,2542893216,NaN,N
23,Associate Auctioneer,17685,SAN SABA,"BARCLIFT, AUSTIN TYLER",NaN,NaN,NaN,NaN,3172018,"BARCLIFT, AUSTIN TYLER",119 E KYLE,NaN,BANGS TX 76823,49.0,BROWN,76823,3253727333,NaN,N
24,Associate Auctioneer,17687,HARRIS,"FORD, PATRICIA NORA",NaN,NaN,NaN,NaN,3182017,"FORD, PATRICIA NORA",1414 ATLANTA ST,NaN,DEER PARK TX 77536-4704,201.0,HARRIS,77536,2814797848,NaN,N
25,Associate Auctioneer,17689,DALLAM,"SCHAFER, TIMOTHY RYAN",NaN,NaN,NaN,NaN,4012017,"SCHAFER, TIMOTHY RYAN",12449 US HIGHWAY 385,NaN,DALHART TX 79022,111.0,DALLAM,79022,8062446776,NaN,N
26,Associate Auctioneer,17695,EL PASO,"MARTINEZ, BRANDY MARIE",NaN,NaN,NaN,NaN,4112017,"MARTINEZ, BRANDY MARIE",7120 ALTO REY AVE,NaN,EL PASO TX 79912-2104,141.0,EL PASO,79912,9153733887,NaN,N
27,Associate Auctioneer,17696,POTTER,"CLEMANS, ZACHARY LEE",NaN,NaN,NaN,NaN,4112017,"CLEMANS, ZACHARY LEE",2520 CLIMER CIR,NaN,AMARILLO TX 79124-2319,375.0,POTTER,79124,8066833130,NaN,N
28,Associate Auctioneer,17699,EL PASO,"MARTINEZ, ARTURO",NaN,NaN,NaN,NaN,4182017,"MARTINEZ, ARTURO",7120 ALTO REY AVE,NaN,EL PASO TX 79912-2104,141.0,EL PASO,79912,9153733887,NaN,N
29,Associate Auctioneer,17706,GRAYSON,"CARSON, DAVID WADE",NaN,NaN,NaN,NaN,4252017,"CARSON, DAVID WADE",1510 S COLLINS FWY,NaN,HOWE TX 75459-4752,181.0,GRAYSON,75459,9035325501,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597785,Water Well Driller/Pump Installer,59847,MONTGOMERY,"SNUFFER, KENNETH DAVID",NaN,NaN,NaN,NaN,9162017,"SNUFFER, KENNETH DAVID",13895 E FM 1097 RD,NaN,WILLIS TX 77378-4347,339.0,MONTGOMERY,77378,9.36857e+09,W,N
597786,Water Well Driller/Pump Installer,59856,BEXAR,"MARTINEZ, JUAN R",NaN,NaN,NaN,NaN,9192017,"MARTINEZ, JUAN R",4412 BLUEMEL RD,NaN,SAN ANTONIO TX 78240-1007,29.0,BEXAR,78240,2.10698e+09,M,N
597787,Water Well Driller/Pump Installer,59857,DEAF SMITH,"YOSTEN, BLAKE JOSEPH",NaN,NaN,NaN,NaN,9192017,"YOSTEN, BLAKE JOSEPH",608 N 25 MILE AVE,NaN,HEREFORD TX 79045-3020,117.0,DEAF SMITH,79045,8.06365e+09,KP,N
597788,Water Well Driller/Pump Installer,59858,MIDLAND,"CLICK, JAY MARCUS",NaN,NaN,NaN,NaN,9202017,"CLICK, JAY MARCUS",9701 FM 307,NaN,MIDLAND TX 79706-5112,329.0,MIDLAND,79706,4.32682e+09,W,N
597789,Water Well Driller/Pump Installer,59862,OUT OF STATE,"PENSE, LARRY WAYNE",NaN,NaN,NaN,NaN,9222017,"PENSE, LARRY WAYNE",654 W 138TH ST,NaN,GLENPOOL OK 74033-3445,999.0,OUT OF STATE,74033,9.18322e+09,W,N
597790,Water Well Driller/Pump Installer,59877,OUT OF STATE,"LARA, STEVEN D",NaN,NaN,NaN,NaN,10042017,"LARA, STEVEN D",3922 E UNIVERSITY DR STE 1,NaN,PHOENIX AZ 85034-2208,999.0,OUT OF STATE,85034,6.02453e+09,M,N
597791,Water Well Driller/Pump Installer,59878,WHEELER,"SMITH, JACE E",NaN,NaN,NaN,NaN,10062017,"SMITH, JACE E",8550 FM 3182,NaN,MOBEETIE TX 79061-4701,483.0,WHEELER,79061,8.06827e+09,KLPT,N
597792,Water Well Driller/Pump Installer,59879,MADISON,"BINNICKER, RICHARD ALLEN",NaN,NaN,NaN,NaN,10062017,"BINNICKER, RICHARD ALLEN",103 S MADISON ST,NaN,MADISONVILLE TX 77864-1902,313.0,MADISON,77864,9.36349e+09,PW,N
597793,Water Well Driller/Pump Installer,59886,TARRANT,"CHAVEZ, FRANCISCO JAVIER",NaN,NaN,NaN,NaN,10172017,"CHAVEZ, FRANCISCO JAVIER",2415 CULLEN ST,NaN,FORT WORTH TX 76107-1411,439.0,TARRANT,76107,8.17877e+09,M,N
597794,Water Well Driller/Pump Installer,59887,DEAF SMITH,"GUERRERO, REY S",NaN,NaN,NaN,NaN,10172017,"GUERRERO, REY S",PO BOX 871,NaN,HEREFORD TX 79045-0871,117.0,DEAF SMITH,79045,8.06364e+09,KLPT,N
597795,Water Well Driller/Pump Installer,59889,BURNET,"SAVAGE, CROCKETT NATHANIEL",NaN,NaN,NaN,NaN,10192017,"SAVAGE, CROCKETT NATHANIEL",1351 FM 1980,NaN,MARBLE FALLS TX 78654-7385,53.0,BURNET,78654,8.30693e+09,P,N
597796,Water Well Driller/Pump Installer,59890,OUT OF STATE,"ADAMS, AARON J",NaN,NaN,NaN,NaN,10192017,"ADAMS, AARON J",3922 E UNIVERSITY DR STE 1,NaN,PHOENIX AZ 85034-2208,999.0,OUT OF STATE,85034,6.02453e+09,M,N
597797,Water Well Driller/Pump Installer,59892,MIDLAND,"SCOTT, JAMES A",NaN,NaN,NaN,NaN,10312017,"SCOTT, JAMES A",415 W WALL ST STE 1300,NaN,MIDLAND TX 79701-4417,329.0,MIDLAND,79701,4.32558e+09,W,N
597798,Water Well Driller/Pump Installer,59896,BREWSTER,"HILL, RYAN WADE",NaN,NaN,NaN,NaN,11142017,"HILL, RYAN WADE",5010 TED ST,NaN,ALPINE TX 79830-1049,43.0,BREWSTER,79830,4.32294e+09,KLP,N
597799,Water Well Driller/Pump Installer,59901,HAYS,"THOMPSON, JARED W T",NaN,NaN,NaN,NaN,11222017,"THOMPSON, JARED W T",185 ANGEL FIRE RD,NaN,DRIPPING SPRINGS TX 78620-2477,209.0,HAYS,78620,5.12894e+09,KP,N
597800,Water Well Driller/Pump Installer,59902,DENTON,"THOMAS, WESLEY WAYNE",NaN,NaN,NaN,NaN,11282017,"THOMAS, WESLEY WAYNE",15035 US HIGHWAY 287,NaN,BOWIE TX 76230-5969,337.0,MONTAGUE,76230,9.40873e+09,W,N
597801,Water Well Driller/Pump Installer,59904,BOSQUE,"JURGENSEN, JOSHUA MARK",NaN,NaN,NaN,NaN,11292017,"JURGENSEN, JOSHUA MARK",18099 N HIGHWAY 6,NaN,VALLEY MILLS TX 76689-2963,35.0,BOSQUE,76689,2.54933e+09,KPT,N
597802,Water Well Driller/Pump Installer,59905,HAYS,"MARSH, AARON ANDREW",NaN,NaN,NaN,NaN,12012017,"MARSH, AARON ANDREW",31866 RANCH ROAD 12,NaN,DRIPPING SPRINGS TX 78620-4097,209.0,HAYS,78620,5.12858e+09,P,N
597803,Water Well Driller/Pump Installer,59907,UVALDE,"KILLOUGH, BRUCE WAYNE",NaN,NaN,NaN,NaN,12052017,"KILLOUGH, BRUCE WAYNE",428 MAIN ST,NaN,UTOPIA TX 78884-2602,463.0,UVALDE,78884,8.30966e+09,KP,N
597804,Water Well Driller/Pump Installer,59908,COLLINGSWORTH,"FAULKS, CARSON SLADE",NaN,NaN,NaN,NaN,12062017,"FAULKS, CARSON SLADE",4243 FM 1547,NaN,QUAIL TX 79251-4126,87.0,COLLINGSWORTH,79251,8.06898e+09,KLPTW,N
597805,Water Well Driller/Pump Installer,59911,ATASCOSA,"ATKINS, BRANDON BUCHANAN",NaN,NaN,NaN,NaN,12132017,"ATKINS, BRANDON BUCHANAN",1209 BENSDALE RD,NaN,PLEASANTON TX 78064-1733,13.0,ATASCOSA,78064,8.30281e+09,KPT,N
597806,Water Well Driller/Pump Installer,59912,OUT OF STATE,"WILLIAMS, MARC R",NaN,NaN,NaN,NaN,12152017,"WILLIAMS, MARC R",3922 E UNIVERSITY DR STE 1,NaN,PHOENIX AZ 85034-2208,999.0,OUT OF STATE,85034,6.02453e+09,M,N
597807,Water Well Driller/Pump Installer,59913,LIMESTONE,"WINSTEAD, CLINTON WADE",NaN,NaN,NaN,NaN,12262017,"WINSTEAD, CLINTON WADE",151 PRIVATE ROAD 5762B,NaN,GROESBECK TX 76642-2304,293.0,LIMESTONE,76642,2.54729e+09,W,N
597808,Water Well Driller/Pump Installer,59926,HENDERSON,"LILLEY, CLINTON",NaN,NaN,NaN,NaN,1132018,"LILLEY, CLINTON",1301 E CORSICANA ST,NaN,ATHENS TX 75751-2236,213.0,HENDERSON,75751,9.03675e+09,KLP,N
597809,Water Well Driller/Pump Installer,59929,BOSQUE,"WOODS, JACOB R",NaN,NaN,NaN,NaN,1232018,"WOODS, JACOB R",18099 N HIGHWAY 6,NaN,VALLEY MILLS TX 76689-2963,35.0,BOSQUE,76689,2.54933e+09,P,N
597810,Water Well Driller/Pump Installer,59930,TOM GREEN,"ABEL, JUSTIN C",NaN,NaN,NaN,NaN,1232018,"ABEL, JUSTIN C",6601 RM HIGHWAY 853,NaN,SAN ANGELO TX 76901-9716,451.0,TOM GREEN,76901,3.2595e+09,KP,N
597811,Water Well Driller/Pump Installer,59931,RUNNELS,"GRAY, MATTHEW BRYAN",NaN,NaN,NaN,NaN,1232018,"GRAY, MATTHEW BRYAN",401 VICTOR ST,NaN,ROWENA TX 76875-2608,399.0,RUNNELS,76875,3.25442e+09,KLPW,N
597812,Water Well Driller/Pump Installer,59934,LAVACA,"MAYER, DAVID W",NaN,NaN,NaN,NaN,1272018,"MAYER, DAVID W",966 FM 318 E,NaN,YOAKUM TX 77995-6786,285.0,LAVACA,77995,3.61293e+09,P,N
597813,Water Well Driller/Pump Installer,59936,HOCKLEY,"FRIESEN, FRANCISCO FEHR",NaN,NaN,NaN,NaN,2132018,"FRIESEN, FRANCISCO FEHR",3686 JAMAICA RD,NaN,LEVELLAND TX 79336-9124,219.0,HOCKLEY,79336,8.06598e+09,W,N
597814,Water Well Driller/Pump Installer,59941,WILSON,"BAUER, DAVID A",NaN,NaN,NaN,NaN,2162018,"BAUER, DAVID A",2590 HEINEN RD,NaN,FLORESVILLE TX 78114-6076,493.0,WILSON,78114,8.30392e+09,W,N

## 2. That looks terrible, let's add column names.

It apparently doesn't have headers! **Read the file in again, but setting your own column names**. Their [current data dictionary might not perfectly match](https://www.opendatanetwork.com/dataset/data.texas.gov/7358-krk7), but you can use it to understand what the columns are. For the dataset we're using, the order goes like this:

* LICTYPE
* LICNUMBER
* BIZCOUNTY
* BIZNAME
* BIZLINE1
* BIZLINE2
* BIZCITYSTATE
* BIZTELEPHONE
* EXPIRATION
* OWNER
* MAILLINE1
* MAILLINE2
* MAILCITYSTATE
* MAILCOUNTYCODE
* MAILCOUNTY
* MAILZIP
* TELEPHONE
* LICSUBTYPE
* CEFLAG

**Note:** You can rename the columns to things that make sense - "expiration" is a little more manageable than "LICENSE EXPIRATION DATE (MMDDCCYY)". I've named my License Type column LICTYPE, so if you haven't you'll have to change the rest of my sample code to match.

In [3]:
df.columns = ['LICTYPE',
'LICNUMBER',
'BIZCOUNTY',
'BIZNAME',
'BIZLINE1',
'BIZLINE2',
'BIZCITYSTATE',
'BIZTELEPHONE',
'EXPIRATION',
'OWNER',
'MAILLINE1',
'MAILLINE2',
'MAILCITYSTATE',
'MAILCOUNTYCODE',
'MAILCOUNTY',
'MAILZIP',
'TELEPHONE',
'LICSUBTYPE',
'CEFLAG']

# 3. Force string columns to be strings

The county code and expiration dates are being read in as numbers, which is going to cause some trouble later on. You can force a column to be a certain type (most usually strings) when reading it in with the following code:

    df = pd.read_csv("your-filename.csv", dtype={"colname1": str, "colname2": str})

You don't need to do it for every column, just the ones you want to force!

**Re-import the file, forcing the expiration date, license number, mailing address county code, mailing zip code and telephone to all be strings.**

In [4]:
df = pd.read_csv("licfile.csv", dtype= str)

df.columns = ['LICTYPE',
'LICNUMBER',
'BIZCOUNTY',
'BIZNAME',
'BIZLINE1',
'BIZLINE2',
'BIZCITYSTATE',
'BIZTELEPHONE',
'EXPIRATION',
'OWNER',
'MAILLINE1',
'MAILLINE2',
'MAILCITYSTATE',
'MAILCOUNTYCODE',
'MAILCOUNTY',
'MAILZIP',
'TELEPHONE',
'LICSUBTYPE',
'CEFLAG']

Check the data types of your columns to be sure! If you do it right they'll be `object` (not `str`, oddly).

In [5]:
df.dtypes

LICTYPE           object
LICNUMBER         object
BIZCOUNTY         object
BIZNAME           object
BIZLINE1          object
BIZLINE2          object
BIZCITYSTATE      object
BIZTELEPHONE      object
EXPIRATION        object
OWNER             object
MAILLINE1         object
MAILLINE2         object
MAILCITYSTATE     object
MAILCOUNTYCODE    object
MAILCOUNTY        object
MAILZIP           object
TELEPHONE         object
LICSUBTYPE        object
CEFLAG            object
dtype: object

## 4. Convert those expiration dates from MMDDYYYY to YYYY-MM-DD

List slicing forever! It's the thing with the `[]`. There are like five ways to do this one.

In [6]:
dates = df['EXPIRATION']

dates
    
date_list = []

for date in dates:
    date_list.append(f'[{date}]')

print(date_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

Check the first five expirations to make sure they look right.

In [7]:
#Jupyter Notebook says the data rate has been exceeded???

# PART TWO: LOOKING AT LICENSES

## 5. What are the top 10 most common licenses?

In [8]:
df['LICTYPE'].value_counts(normalize = True).head(10)

Cosmetology Operator        0.255965
Apprentice Electrician      0.187214
Cosmetology Manicurist      0.083901
Journeyman Electrician      0.064615
A/C Technician              0.047330
Cosmetology Esthetician     0.039973
Cosmetology Beauty Salon    0.039912
Master Electrician          0.028456
A/C Contractor              0.027722
Barber, Class A             0.027117
Name: LICTYPE, dtype: float64

## 6. What are the top 10 least common?

In [9]:
df['LICTYPE'].value_counts(normalize = True).tail(10)

Elevator Responsible Party CE Provider             0.000014
Mobile Cosmetology Esthetician Specialty Saloon    0.000008
Barber Hair Braiding Shop                          0.000007
Barber Hair Weaving Shop                           0.000007
Booting CE Provider                                0.000005
Mobile Cosmetology Manicure Specialty Saloon       0.000003
Cosmetology Wig Instructor                         0.000003
Licensed Court Interpreter CE Provider             0.000003
Mobile Cosmetology Esthetician/Manicure Saloon     0.000003
Legal Service Contract Admin                       0.000002
Name: LICTYPE, dtype: float64

## 7. Try to select everyone who is any type of electrician.

You're going to get an error about `"cannot index with vector containing NA / NaN values"`. Let's work our way in there.

In [10]:
# Yes I know I left this in here, it's a learning experience!
df[df['LICTYPE'].str.contains("Electrician")]

ValueError: cannot index with vector containing NA / NaN values

## 8. How many of the rows of LICTYPE are NaN?

In [ ]:
df['LICTYPE'].isnull().value_counts()

Over 7000 licenses don't have types! As a result, when we look for license types with electricians - aka do `df['LICTYPE'].str.contains("Electrician")` - we get three results:

* `True` means `LICTYPE` exists and contains `"Electrician"`
* `False` means `LICTYPE` exists and does not contain `"Electrician"`
* `NaN` means `LICTYPE` does not exist for that row

## 9. Actually getting everyone who is an electrician

This doesn't work when trying to select electricians, though, as NaN is a no-go for a filter. We *could* filter out everywhere the LICTYPE is null, but we could also cheat a little and say "replace all of the `NaN` values with `False` values."

`.fillna(False)` will take every `NaN` and replace it with `False`.

In [ ]:
df['LICTYPE'] = df['LICTYPE'].fillna(0, inplace=True)

## 10. What's the most popular kind of electrician?

In [ ]:
df[df['LICTYPE'].isnull()]

In [ ]:
df['LICTYPE'].astype('str')

In [ ]:
df[df['LICTYPE'].str.contains("Electrician")]

## 11. Graph it, with the largest bar on top.

In [ ]:
# previous code not working

## 12. How many sign electricians are there?

There are a few ways to do this one.

In [ ]:
# previous code not working

# PART THREE: LOOKING AT LAST NAMES

## 13. Extract every owner's last name

You want everything before the comma. We've done this before (in a few different ways!).

* **Hint:** If you get an error about missing or `NaN` data, you might use `.fillna('')` to replace every empty owner name with an empty string. This might not happen to you, though, depending on how you do it!

* **Hint:** You probably want to do `expand=False` on your extraction to make sure it comes out as a series instead of a dataframe.

In [32]:
df['BIZNAME'].str.split(",").str.get(0)

0            WILLIAMS
1             GUEVARA
2              BOWERS
3              DEMSKY
4            THOMPSON
5              TUCKER
6              COOPER
7         BLANKENSHIP
8               DAWES
9              LESTER
10            MANCILL
11         HUDDLESTON
12             JORDAN
13              IRWIN
14               HALL
15              JAMES
16             SIDAWI
17              SMITH
18           FERGUSON
19           MCKINLEY
20             SOWELL
21             SEVIER
22         SOMERVILLE
23           BARCLIFT
24               FORD
25            SCHAFER
26           MARTINEZ
27            CLEMANS
28           MARTINEZ
29             CARSON
             ...
597785        SNUFFER
597786       MARTINEZ
597787         YOSTEN
597788          CLICK
597789          PENSE
597790           LARA
597791          SMITH
597792      BINNICKER
597793         CHAVEZ
597794       GUERRERO
597795         SAVAGE
597796          ADAMS
597797          SCOTT
597798           HILL
597799       THOMPSON
597800         THOMAS
597801      JURGENSEN
597802          MARSH
597803       KILLOUGH
597804         FAULKS
597805         ATKINS
597806       WILLIAMS
597807       WINSTEAD
597808         LILLEY
597809          WOODS
597810           ABEL
597811           GRAY
597812          MAYER
597813        FRIESEN
597814          BAUER
Name: BIZNAME, Length: 597815, dtype: object

## 14. Save the last name into a new column

Then check to make sure it exists, and you successfully saved it into the dataframe.

In [33]:
df['last_name'] = df['BIZNAME'].str.split(",").str.get(0)

In [36]:
df

,LICTYPE,LICNUMBER,BIZCOUNTY,BIZNAME,BIZLINE1,BIZLINE2,BIZCITYSTATE,BIZTELEPHONE,EXPIRATION,OWNER,MAILLINE1,MAILLINE2,MAILCITYSTATE,MAILCOUNTYCODE,MAILCOUNTY,MAILZIP,TELEPHONE,LICSUBTYPE,CEFLAG,last_name
0,Associate Auctioneer,7962,UPSHUR,"WILLIAMS, JON ANDRE",NaN,NaN,NaN,NaN,12292017,"WILLIAMS, JON ANDRE",228 FM 1252,NaN,KILGORE TX 75662,0183,GREGG,75662,9039187899,NaN,N,WILLIAMS
1,Associate Auctioneer,8406,WILSON,"GUEVARA, JUAN ANTONIO",NaN,NaN,NaN,NaN,09262017,"GUEVARA, JUAN ANTONIO",6909 HWY 181,NaN,POTH TX 78147,0493,WILSON,78147,NaN,NaN,N,GUEVARA
2,Associate Auctioneer,10543,HARRIS,"BOWERS, JAMES BRISCOE II",NaN,NaN,NaN,NaN,11042017,"BOWERS, JAMES BRISCOE II",6767 NORTH FWY,NaN,HOUSTON TX 77076-2027,0201,HARRIS,77076,7136445566,NaN,N,BOWERS
3,Associate Auctioneer,10642,BELL,"DEMSKY, JOHN EDWARD",NaN,NaN,NaN,NaN,02252018,"DEMSKY, JOHN EDWARD",130 E CLARK ST,NaN,BARTLETT TX 76511,0027,BELL,76511,2549852228,NaN,N,DEMSKY
4,Associate Auctioneer,15650,OUT OF STATE,"THOMPSON, RANDY D",NaN,NaN,NaN,NaN,05042017,"THOMPSON, RANDY D",10995 BELLEVILLE RD,NaN,RINGLING OK 73456,0999,OUT OF STATE,73456,5802765961,NaN,N,THOMPSON
5,Associate Auctioneer,15698,OUT OF STATE,"TUCKER, MONTE EARL",NaN,NaN,NaN,NaN,06162017,"TUCKER, MONTE EARL",19139 HIGHWAY 6,NaN,SAYRE OK 73662-6080,0999,OUT OF STATE,73662,5802250269,NaN,N,TUCKER
6,Associate Auctioneer,15810,MILAM,"COOPER, THOMAS JAMES",NaN,NaN,NaN,NaN,03182017,"COOPER, THOMAS JAMES",346 MAIN ST,NaN,ROSEBUD TX 76570,0145,FALLS,76570,2815078713,NaN,N,COOPER
7,Associate Auctioneer,15835,OUT OF STATE,"BLANKENSHIP, KERRY NEIL",NaN,NaN,NaN,NaN,05042017,"BLANKENSHIP, KERRY NEIL",10664 BELLEVILLE RD,NaN,RINGLING OK 73456-2014,0999,OUT OF STATE,73456,5802765961,NaN,N,BLANKENSHIP
8,Associate Auctioneer,16784,OUT OF STATE,"DAWES, NICHOLAS MORGAN",NaN,NaN,NaN,NaN,10192017,"DAWES, NICHOLAS MORGAN",3500 MAPLE AVENUE 17TH FLOOR,NaN,DALLAS TX 75219,0113,DALLAS,75219,2144091137,NaN,N,DAWES
9,Associate Auctioneer,16893,LAMAR,"LESTER, TIMMY EUGENE",NaN,NaN,NaN,NaN,08192017,"LESTER, TIMMY EUGENE",167 COUNTY ROAD 16380,NaN,CUNNINGHAM TX 75434,0277,LAMAR,75434,9037825759,NaN,N,LESTER
10,Associate Auctioneer,16969,NACOGDOCHES,"MANCILL, MARK DUANE",NaN,NaN,NaN,NaN,04212017,"MANCILL, MARK DUANE",116 TRAILWOOD CIR,NaN,LUFKIN TX 75904-4331,0005,ANGELINA,75904,9366749636,NaN,N,MANCILL
11,Associate Auctioneer,16990,BEXAR,"HUDDLESTON, SHAWN ALAN",NaN,NaN,NaN,NaN,02182017,"HUDDLESTON, SHAWN ALAN",3903 EISENHOUER RD,NaN,SAN ANTONIO TX 78218,0029,BEXAR,78218,2106815425,NaN,N,HUDDLESTON
12,Associate Auctioneer,17072,ECTOR,"JORDAN, JAMES EUGENE",NaN,NaN,NaN,NaN,02182018,"JORDAN, JAMES EUGENE",6190 CARGO RD,NaN,ODESSA TX 79762,0135,ECTOR,79762,4322722266,NaN,N,JORDAN
13,Associate Auctioneer,17108,KAUFMAN,"IRWIN, MICHAEL RICHARD",NaN,NaN,NaN,NaN,02252017,"IRWIN, MICHAEL RICHARD",8513 MICHAEL TALTY AVE,NaN,TERRELL TX 75160-7592,0257,KAUFMAN,75160,4695951384,NaN,N,IRWIN
14,Associate Auctioneer,17241,HOOD,"HALL, WESLEY RYON",NaN,NaN,NaN,NaN,01252018,"HALL, WESLEY RYON",13016 HWY 36,NaN,COMANCHE TX 76442-7305,0093,COMANCHE,76442,3253565950,NaN,N,HALL
15,Associate Auctioneer,17242,ERATH,"JAMES, BACHUS ROSS",NaN,NaN,NaN,NaN,05042017,"JAMES, BACHUS ROSS",471 N HARBIN DR,NaN,STEPHENVILLE TX 76401-2860,0143,ERATH,76401,2545928394,NaN,N,JAMES
16,Associate Auctioneer,17669,JOHNSON,"SIDAWI, JOSEPH JAMES",NaN,NaN,NaN,NaN,02082017,"SIDAWI, JOSEPH JAMES",2032 W FM 917,NaN,JOSHUA TX 76058-6060,0251,JOHNSON,76058,8173200833,NaN,N,SIDAWI
17,Associate Auctioneer,17671,MILLS,"SMITH, DAVID JAMES",NaN,NaN,NaN,NaN,02082018,"SMITH, DAVID JAMES",1110 US HIGHWAY 84 WEST,NaN,GOLDTHWAITE TX 76844,0333,MILLS,76844,3259386750,NaN,N,SMITH
18,Associate Auctioneer,17672,BROWN,"FERGUSON, JACKIE LEE",NaN,NaN,NaN,NaN,02092018,"FERGUSON, JACKIE LEE",119 E KYLE ST,NaN,BANGS TX 76823,0049,BROWN,76823,3253727333,NaN,N,FERGUSON
19,Associate Auctioneer,17675,UPSHUR,"MCKINLEY, MATTHEW D",NaN,NaN,NaN,NaN,02182018,"MCKINLEY, MATTHEW D",805 BROADWAY AVE,NaN,GLADEWATER TX 75647-2415,0183,GREGG,75647,9038453830,NaN,N,MCKINLEY
20,Associate Auctioneer,17676,JOHNSON,"SOWELL, KALEN BRICE",NaN,NaN,NaN,NaN,02182018,"SOWELL, KALEN BRICE",111 N BROADWAY ST,NaN,CRESSON TX 76035,0221,HOOD,76035,8173821530,NaN,N,SOWELL
21,Associate Auctioneer,17679,ELLIS,"SEVIER, VIRGINIA A",NaN,NaN,NaN,NaN,02252018,"SEVIER, VIRGINIA A",212 S ROGERS,NaN,WAXAHACHIE TX 75165,0139,ELLIS,75165,9726930572,NaN,N,SEVIER
22,Associate Auctioneer,17680,BELL,"SOMERVILLE, CAL W",NaN,NaN,NaN,NaN,02252017,"SOMERVILLE, CAL W",202 BRANDY LOOP,NaN,KILLEEN TX 76549-9049,0027,BELL,76549,2542893216,NaN,N,SOMERVILLE
23,Associate Auctioneer,17685,SAN SABA,"BARCLIFT, AUSTIN TYLER",NaN,NaN,NaN,NaN,03172018,"BARCLIFT, AUSTIN TYLER",119 E KYLE,NaN,BANGS TX 76823,0049,BROWN,76823,3253727333,NaN,N,BARCLIFT
24,Associate Auctioneer,17687,HARRIS,"FORD, PATRICIA NORA",NaN,NaN,NaN,NaN,03182017,"FORD, PATRICIA NORA",1414 ATLANTA ST,NaN,DEER PARK TX 77536-4704,0201,HARRIS,77536,2814797848,NaN,N,FORD
25,Associate Auctioneer,17689,DALLAM,"SCHAFER, TIMOTHY RYAN",NaN,NaN,NaN,NaN,04012017,"SCHAFER, TIMOTHY RYAN",12449 US HIGHWAY 385,NaN,DALHART TX 79022,0111,DALLAM,79022,8062446776,NaN,N,SCHAFER
26,Associate Auctioneer,17695,EL PASO,"MARTINEZ, BRANDY MARIE",NaN,NaN,NaN,NaN,04112017,"MARTINEZ, BRANDY MARIE",7120 ALTO REY AVE,NaN,EL PASO TX 79912-2104,0141,EL PASO,79912,9153733887,NaN,N,MARTINEZ
27,Associate Auctioneer,17696,POTTER,"CLEMANS, ZACHARY LEE",NaN,NaN,NaN,NaN,04112017,"CLEMANS, ZACHARY LEE",2520 CLIMER CIR,NaN,AMARILLO TX 79124-2319,0375,POTTER,79124,8066833130,NaN,N,CLEMANS
28,Associate Auctioneer,17699,EL PASO,"MARTINEZ, ARTURO",NaN,NaN,NaN,NaN,04182017,"MARTINEZ, ARTURO",7120 ALTO REY AVE,NaN,EL PASO TX 79912-2104,0141,EL PASO,79912,9153733887,NaN,N,MARTINEZ
29,Associate Auctioneer,17706,GRAYSON,"CARSON, DAVID WADE",NaN,NaN,NaN,NaN,04252017,"CARSON, DAVID WADE",1510 S COLLINS FWY,NaN,HOWE TX 75459-4752,0181,GRAYSON,75459,9035325501,NaN,N,CARSON
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597785,Water Well Driller/Pump Installer,59847,MONTGOMERY,"SNUFFER, KENNETH DAVID",NaN,NaN,NaN,NaN,09162017,"SNUFFER, KENNETH DAVID",13895 E FM 1097 RD,NaN,WILLIS TX 77378-4347,0339,MONTGOMERY,77378,9368566374,W,N,SNUFFER
597786,Water Well Driller/Pump Installer,59856,BEXAR,"MARTINEZ, JUAN R",NaN,NaN,NaN,NaN,09192017,"MARTINEZ, JUAN R",4412 BLUEMEL RD,NaN,SAN ANTONIO TX 78240-1007,0029,BEXAR,78240,2106977114,M,N,MARTINEZ
597787,Water Well Driller/Pump Installer,59857,DEAF SMITH,"YOSTEN, BLAKE JOSEPH",NaN,NaN,NaN,NaN,09192017,"YOSTEN, BLAKE JOSEPH",608 N 25 MILE AVE,NaN,HEREFORD TX 79045-3020,0117,DEAF SMITH,79045,8063646140,KP,N,YOSTEN
597788,Water Well Driller/Pump Installer,59858,MIDLAND,"CLICK, JAY MARCUS",NaN,NaN,NaN,NaN,09202017,"CLICK, JAY MARCUS",9701 FM 307,NaN,MIDLAND TX 79706-5112,0329,MIDLAND,79706,4326820703,W,N,CLICK
597789,Water Well Driller/Pump Installer,59862,OUT OF STATE,"PENSE, LARRY WAYNE",NaN,NaN,NaN,NaN,09222017,"PENSE, LARRY WAYNE",654 W 138TH ST,NaN,GLENPOOL OK 74033-3445,0999,OUT OF STATE,74033,9183223095,W,N,PENSE
597790,Water Well Driller/Pump Installer,59877,OUT OF STATE,"LARA, STEVEN D",NaN,NaN,NaN,NaN,10042017,"LARA, STEVEN D",3922 E UNIVERSITY DR STE 1,NaN,PHOENIX AZ 85034-2208,0999,OUT OF STATE,85034,6024533252,M,N,LARA
597791,Water Well Driller/Pump Installer,59878,WHEELER,"SMITH, JACE E",NaN,NaN,NaN,NaN,10062017,"SMITH, JACE E",8550 FM 3182,NaN,MOBEETIE TX 79061-4701,0483,WHEELER,79061,8068265975,KLPT,N,SMITH
597792,Water Well Driller/Pump Installer,59879,MADISON,"BINNICKER, RICHARD ALLEN",NaN,NaN,NaN,NaN,10062017,"BINNICKER, RICHARD ALLEN",103 S MADISON ST,NaN,MADISONVILLE TX 77864-1902,0313,MADISON,77864,9363485838,PW,N,BINNICKER
597793,Water Well Driller/Pump Installer,59886,TARRANT,"CHAVEZ, FRANCISCO JAVIER",NaN,NaN,NaN,NaN,10172017,"CHAVEZ, FRANCISCO JAVIER",2415 CULLEN ST,NaN,FORT WORTH TX 76107-1411,0439,TARRANT,76107,8178770866,M,N,CHAVEZ
597794,Water Well Driller/Pump Installer,59887,DEAF SMITH,"GUERRERO, REY S",NaN,NaN,NaN,NaN,10172017,"GUERRERO, REY S",PO BOX 871,NaN,HEREFORD TX 79045-0871,0117,DEAF SMITH,79045,8063643109,KLPT,N,GUERRERO
597795,Water Well Driller/Pump Installer,59889,BURNET,"SAVAGE, CROCKETT NATHANIEL",NaN,NaN,NaN,NaN,10192017,"SAVAGE, CROCKETT NATHANIEL",1351 FM 1980,NaN,MARBLE FALLS TX 78654-7385,0053,BURNET,78654,8306932340,P,N,SAVAGE
597796,Water Well Driller/Pump Installer,59890,OUT OF STATE,"ADAMS, AARON J",NaN,NaN,NaN,NaN,10192017,"ADAMS, AARON J",3922 E UNIVERSITY DR STE 1,NaN,PHOENIX AZ 85034-2208,0999,OUT OF STATE,85034,6024533252,M,N,ADAMS
597797,Water Well Driller/Pump Installer,59892,MIDLAND,"SCOTT, JAMES A",NaN,NaN,NaN,NaN,10312017,"SCOTT, JAMES A",415 W WALL ST STE 1300,NaN,MIDLAND TX 79701-4417,0329,MIDLAND,79701,4325578821,W,N,SCOTT
597798,Water Well Driller/Pump Installer,59896,BREWSTER,"HILL, RYAN WADE",NaN,NaN,NaN,NaN,11142017,"HILL, RYAN WADE",5010 TED ST,NaN,ALPINE TX 79830-1049,0043,BREWSTER,79830,4322942335,KLP,N,HILL
597799,Water Well Driller/Pump Installer,59901,HAYS,"THOMPSON, JARED W T",NaN,NaN,NaN,NaN,11222017,"THOMPSON, JARED W T",185 ANGEL FIRE RD,NaN,DRIPPING SPRINGS TX 78620-2477,0209,HAYS,78620,5128944221,KP,N,THOMPSON
597800,Water Well Driller/Pump Installer,59902,DENTON,"THOMAS, WESLEY WAYNE",NaN,NaN,NaN,NaN,11282017,"THOMAS, WESLEY WAYNE",15035 US HIGHWAY 287,NaN,BOWIE TX 76230-5969,0337,MONTAGUE,76230,9408726992,W,N,THOMAS
597801,Water Well Driller/Pump Installer,59904,BOSQUE,"JURGENSEN, JOSHUA MARK",NaN,NaN,NaN,NaN,11292017,"JURGENSEN, JOSHUA MARK",18099 N HIGHWAY 6,NaN,VALLEY MILLS TX 76689-2963,0035,BOSQUE,76689,2549326251,KPT,N,JURGENSEN
597802,Water Well Driller/Pump Installer,59905,HAYS,"MARSH, AARON ANDREW",NaN,NaN,NaN,NaN,12012017,"MARSH, AARON ANDREW",31866 RANCH ROAD 12,NaN,DRIPPING SPRINGS TX 78620-4097,0209,HAYS,78620,5128584375,P,N,MARSH
597803,Water Well Driller/Pump Installer,59907,UVALDE,"KILLOUGH, BRUCE WAYNE",NaN,NaN,NaN,NaN,12052017,"KILLOUGH, BRUCE WAYNE",428 MAIN ST,NaN,UTOPIA TX 78884-2602,0463,UVALDE,78884,8309663456,KP,N,KILLOUGH
597804,Water Well Driller/Pump Installer,59908,COLLINGSWORTH,"FAULKS, CARSON SLADE",NaN,NaN,NaN,NaN,12062017,"FAULKS, CARSON SLADE",4243 FM 1547,NaN,QUAIL TX 79251-4126,0087,COLLINGSWORTH,79251,8068981609,KLPTW,N,FAULKS
597805,Water Well Driller/Pump Installer,59911,ATASCOSA,"ATKINS, BRANDON BUCHANAN",NaN,NaN,NaN,NaN,12132017,"ATKINS, BRANDON BUCHANAN",1209 BENSDALE RD,NaN,PLEASANTON TX 78064-1733,0013,ATASCOSA,78064,8302812400,KPT,N,ATKINS
597806,Water Well Driller/Pump Installer,59912,OUT OF STATE,"WILLIAMS, MARC R",NaN,NaN,NaN,NaN,12152017,"WILLIAMS, MARC R",3922 E UNIVERSITY DR STE 1,NaN,PHOENIX AZ 85034-2208,0999,OUT OF STATE,85034,6024533252,M,N,WILLIAMS
597807,Water Well Driller/Pump Installer,59913,LIMESTONE,"WINSTEAD, CLINTON WADE",NaN,NaN,NaN,NaN,12262017,"WINSTEAD, CLINTON WADE",151 PRIVATE ROAD 5762B,NaN,GROESBECK TX 76642-2304,0293,LIMESTONE,76642,2547293762,W,N,WINSTEAD
597808,Water Well Driller/Pump Installer,59926,HENDERSON,"LILLEY, CLINTON",NaN,NaN,NaN,NaN,01132018,"LILLEY, CLINTON",1301 E CORSICANA ST,NaN,ATHENS TX 75751-2236,0213,HENDERSON,75751,9036752353,KLP,N,LILLEY
597809,Water Well Driller/Pump Installer,59929,BOSQUE,"WOODS, JACOB R",NaN,NaN,NaN,NaN,01232018,"WOODS, JACOB R",18099 N HIGHWAY 6,NaN,VALLEY MILLS TX 76689-2963,0035,BOSQUE,76689,2549326251,P,N,WOODS
597810,Water Well Driller/Pump Installer,59930,TOM GREEN,"ABEL, JUSTIN C",NaN,NaN,NaN,NaN,01232018,"ABEL, JUSTIN C",6601 RM HIGHWAY 853,NaN,SAN ANGELO TX 76901-9716,0451,TOM GREEN,76901,3259496607,KP,N,ABEL
597811,Water Well Driller/Pump Installer,59931,RUNNELS,"GRAY, MATTHEW BRYAN",NaN,NaN,NaN,NaN,01232018,"GRAY, MATTHEW BRYAN",401 VICTOR ST,NaN,ROWENA TX 76875-2608,0399,RUNNELS,76875,3254422331,KLPW,N,GRAY
597812,Water Well Driller/Pump Installer,59934,LAVACA,"MAYER, DAVID W",NaN,NaN,NaN,NaN,01272018,"MAYER, DAVID W",966 FM 318 E,NaN,YOAKUM TX 77995-6786,0285,LAVACA,77995,3612933168,P,N,MAYER
597813,Water Well Driller/Pump Installer,59936,HOCKLEY,"FRIESEN, FRANCISCO FEHR",NaN,NaN,NaN,NaN,02132018,"FRIESEN, FRANCISCO FEHR",3686 JAMAICA RD,NaN,LEVELLAND TX 79336-9124,0219,HOCKLEY,79336,8065980508,W,N,FRIESEN
597814,Water Well Driller/Pump Installer,59941,WILSON,"BAUER, DAVID A",NaN,NaN,NaN,NaN,02162018,"BAUER, DAVID A",2590 HEINEN RD,NaN,FLORESVILLE TX 78114-6076,0493,WILSON,78114,8303917338,W,N,BAUER

# 15. What are the ten most popular last names?

In [35]:
df['last_name'].value_counts()

NGUYEN                         22355
TRAN                            8167
GARCIA                          5688
LE                              5613
MARTINEZ                        4809
RODRIGUEZ                       4722
HERNANDEZ                       4469
PHAM                            4007
GONZALEZ                        3693
SMITH                           3351
LOPEZ                           3052
PEREZ                           2641
WILLIAMS                        2550
JOHNSON                         2504
RAMIREZ                         2491
HUYNH                           2441
SANCHEZ                         2436
FLORES                          2221
GARZA                           2208
JONES                           2187
VO                              2013
BROWN                           1975
PHAN                            1792
TORRES                          1777
DAVIS                           1739
VU                              1579
TRUONG                          1489
GOMEZ                           1446
REYES                           1364
DANG                            1362
                               ...
MELER                              1
LOECHEL                            1
SALON ARMIJO                       1
OBID                               1
SMARTWATT INC                      1
DIVINE BEAUTY SALON                1
ESTHETIC BEAUTY                    1
TC TAYLOR LLC DBA FACELOGIC        1
A & R PAYROLL SERVICES INC         1
ACQUAYE                            1
WANJOHI                            1
AMAYA RECINOS                      1
ENGLE-BRAZZIL                      1
BAGBY'S BARBER SHOP                1
PRIME SOURCE PAYROLL LP            1
VP NAIL BAR                        1
KOLBABA                            1
KRHOVJAK                           1
RITA'S CUTS AND WAVES              1
CATE'S TOUCH                       1
TEXSUN ELECTRIC                    1
JIMENEZ MEJIA                      1
OCEANS SPA ON BROADWAY             1
PANZARDI                           1
SHAHSWAR                           1
PIRATE ISLAND POOLS LLC            1
FRIEDERMAN                         1
RCI ELECTRICAL SERVICES            1
DAVIS-ORR                          1
MCGILL ELECTRIC                    1
Name: last_name, Length: 128435, dtype: int64

## 16. What are the most popular licenses for people with the last name Nguyen? Tran? Le?

Those are the top 3 last names in Vietnam.

In [61]:
nguyen = df[df['last_name'] == 'NGUYEN']

nguyen['LICTYPE'].value_counts(normalize=True).head()

Cosmetology Manicurist     0.575625
Cosmetology Operator       0.180845
Cosmetology Esthetician    0.128996
Cosmetologist              0.083997
Apprentice Electrician     0.008731
Name: LICTYPE, dtype: float64

In [63]:
tran = df[df['last_name'] == 'TRAN']

tran['LICTYPE'].value_counts(normalize=True).head()

Cosmetology Manicurist     0.572846
Cosmetology Operator       0.180738
Cosmetology Esthetician    0.126455
Cosmetologist              0.087244
Apprentice Electrician     0.011641
Name: LICTYPE, dtype: float64

In [62]:
lee = df[df['last_name'] == 'LEE']

lee['LICTYPE'].value_counts(normalize=True).head()

Cosmetology Operator      0.348110
Apprentice Electrician    0.143416
Cosmetology Manicurist    0.063885
Journeyman Electrician    0.061278
Barber, Class A           0.058670
Name: LICTYPE, dtype: float64

## 17. Now do all of that in one line - most popular licenses for Nguyen, Tran and Le - without using `&`

In [71]:
NTL = df [df['last_name'] == 'NGUYEN' | 'TRAN' | 'LEE']

TypeError: unsupported operand type(s) for |: 'str' and 'str'

## 18. Most popular licenses for Garcia? Rodriguez? Martinez?

Those are the 3 most common last names for self-identifying Hispanics in the USA.

In [72]:
GR = df [df['last_name'] == 'GARCIA' | 'RODRIGUEZ']

TypeError: unsupported operand type(s) for |: 'str' and 'str'

In [81]:
df.last_name

0            WILLIAMS
1             GUEVARA
2              BOWERS
3              DEMSKY
4            THOMPSON
5              TUCKER
6              COOPER
7         BLANKENSHIP
8               DAWES
9              LESTER
10            MANCILL
11         HUDDLESTON
12             JORDAN
13              IRWIN
14               HALL
15              JAMES
16             SIDAWI
17              SMITH
18           FERGUSON
19           MCKINLEY
20             SOWELL
21             SEVIER
22         SOMERVILLE
23           BARCLIFT
24               FORD
25            SCHAFER
26           MARTINEZ
27            CLEMANS
28           MARTINEZ
29             CARSON
             ...
597785        SNUFFER
597786       MARTINEZ
597787         YOSTEN
597788          CLICK
597789          PENSE
597790           LARA
597791          SMITH
597792      BINNICKER
597793         CHAVEZ
597794       GUERRERO
597795         SAVAGE
597796          ADAMS
597797          SCOTT
597798           HILL
597799       THOMPSON
597800         THOMAS
597801      JURGENSEN
597802          MARSH
597803       KILLOUGH
597804         FAULKS
597805         ATKINS
597806       WILLIAMS
597807       WINSTEAD
597808         LILLEY
597809          WOODS
597810           ABEL
597811           GRAY
597812          MAYER
597813        FRIESEN
597814          BAUER
Name: last_name, Length: 597815, dtype: object

## 19. Most popular license for anyone with a last name that ENDS in `-ez`

The answer is not `.str.contains('ez')`, but it isn't necessarily too different. **Make sure your numbers match mine.**

One way involves a `.str.` method that check if a string ends with something, the other way involves a regular expression that has a "end of the string" marker (similar to how we've used `^` for the start of a string before). If you're thinking about the latter, I might take a look at [this page](http://www.rexegg.com/regex-quickstart.html) under "Anchors and Boundaries".

In [96]:
EZ = df[df['last_name'].str.contains('.*?EZ$', na =False)]

EZ['LICTYPE'].value_counts().head(1)

Apprentice Electrician    16065
Name: LICTYPE, dtype: int64

## 20. Get that as a percentage

In [97]:
EZ['LICTYPE'].value_counts(normalize=True).head(1)

Apprentice Electrician    0.353341
Name: LICTYPE, dtype: float64

# PART FOUR: LOOKING AT FIRST NAMES

## 21. Extract the owner's first name

First, a little example of how regular expressions work with pandas.

In [101]:
# Build a dataframe
sample_df = pd.DataFrame([
    { 'name': 'Mary', 'sentence': "I am 90 years old" },
    { 'name': 'Jack', 'sentence': "I am 4 years old" },
    { 'name': 'Anne', 'sentence': "I am 27 years old" },
    { 'name': 'Joel', 'sentence': "I am 13 years old" },
])
# Look at the dataframe
sample_df

   name           sentence
0  Mary  I am 90 years old
1  Jack   I am 4 years old
2  Anne  I am 27 years old
3  Joel  I am 13 years old

In [102]:
# Given the sentence, "I am X years old", extract digits from the middle using ()
# Anything you put in () will be saved as an output.
# If you do expand=True it makes you a dataframe, but we don't want that.
sample_df['sentence'].str.extract("I am (\d+) years old", expand=False)

0    90
1     4
2    27
3    13
Name: sentence, dtype: object

In [103]:
# Save it into a new column
sample_df['age'] = sample_df['sentence'].str.extract("I am (\d+) years old", expand=False)
sample_df.head()

   name           sentence age
0  Mary  I am 90 years old  90
1  Jack   I am 4 years old   4
2  Anne  I am 27 years old  27
3  Joel  I am 13 years old  13

**Now let's think about how we're going to extract the first names.** Begin by looking at a few full names.

In [142]:
df['OWNER'].head(10)

0         WILLIAMS, JON ANDRE
1       GUEVARA, JUAN ANTONIO
2    BOWERS, JAMES BRISCOE II
3         DEMSKY, JOHN EDWARD
4           THOMPSON, RANDY D
5          TUCKER, MONTE EARL
6        COOPER, THOMAS JAMES
7     BLANKENSHIP, KERRY NEIL
8      DAWES, NICHOLAS MORGAN
9        LESTER, TIMMY EUGENE
Name: OWNER, dtype: object

What can you use to find the first name? It helps to say "this is to the left and this is to the right, and I'm going to take anything in the middle."

Once you figure out how to extract it, you can do a `.head(10)` to just look at the first few.

In [ ]:
df['OWNER'].str.extract("J", expand=False)

## 22. Saving the owner's first name

Save the name to a new column, `FIRSTNAME`.

In [134]:
df['FIRSTNAME'] = df['OWNER'].str.extract(",[\s\S]*$", expand=False)

ValueError: pattern contains no capture groups

# 23. Examine everyone without a first name

I purposefully didn't do a nicer regex in order to have some screwed-up results. **How many people are there without an entry in the first name column?**

Your numbers might be different than mine.

In [116]:
df['FIRSTNAME'].isnull().value_counts()

False    516214
True      81601
Name: FIRSTNAME, dtype: int64

What do their names look like?

In [117]:
df[df['FIRSTNAME'].isnull()]

,LICTYPE,LICNUMBER,BIZCOUNTY,BIZNAME,BIZLINE1,BIZLINE2,BIZCITYSTATE,BIZTELEPHONE,EXPIRATION,OWNER,...,MAILCITYSTATE,MAILCOUNTYCODE,MAILCOUNTY,MAILZIP,TELEPHONE,LICSUBTYPE,CEFLAG,last_name,first_name,FIRSTNAME
28021,Appliance Installation Contractor,101,HARRIS,APPLIANCE INSTALLATION BY SPECIAL D LLC,NaN,NaN,NaN,NaN,05232017,APPLIANCE INSTALLATION BY SPECIAL D LLC,...,HOUSTON TX 77093,0201,HARRIS,77093,2815363711,RAIC,N,APPLIANCE INSTALLATION BY SPECIAL D LLC,NaN,NaN
28022,Appliance Installation Contractor,103,DALLAS,CAPITAL DISTRIBUTING INC,NaN,NaN,NaN,NaN,04082017,CAPITAL DISTRIBUTING INC,...,DALLAS TX 75247-6103,0113,DALLAS,75247,2146382681,RAIC,N,CAPITAL DISTRIBUTING INC,NaN,NaN
28023,Appliance Installation Contractor,104,DALLAS,INSTALLCO LLC,NaN,NaN,NaN,NaN,04082017,INSTALLCO LLC,...,DALLAS TX 75247-6103,0113,DALLAS,75247,2142761033,RAIC,N,INSTALLCO LLC,NaN,NaN
28024,Appliance Installation Contractor,107,BOWIE,LAFFERTYS TV & APPLIANCE INC,NaN,NaN,NaN,NaN,03202018,LAFFERTYS TV & APPLIANCE INC,...,TEXARKANA TX 75503,0037,BOWIE,75503,9037942581,RAIC,N,LAFFERTYS TV & APPLIANCE INC,NaN,NaN
28025,Appliance Installation Contractor,108,FREESTONE,BALLARD COMPANY,NaN,NaN,NaN,NaN,04022017,BALLARD COMPANY,...,FAIRFIELD TX 75840,0161,FREESTONE,75840,9033895774,RAIC,N,BALLARD COMPANY,NaN,NaN
28026,Appliance Installation Contractor,109,BEXAR,FACTORY BUILDER STORES LTD,NaN,NaN,NaN,NaN,02072018,FACTORY BUILDER STORES LTD,...,SAN ANTONIO TX 78247,0029,BEXAR,78247,2103499333,RAIC,N,FACTORY BUILDER STORES LTD,NaN,NaN
28027,Appliance Installation Contractor,112,TRAVIS,HARWAY SUPPLY INC,NaN,NaN,NaN,NaN,04112018,HARWAY SUPPLY INC,...,AUSTIN TX 78758,0453,TRAVIS,78758,5124917600,RAIC,N,HARWAY SUPPLY INC,NaN,NaN
28029,Appliance Installation Contractor,115,COLLIN,RODENBAUGH'S INC,NaN,NaN,NaN,NaN,04112017,RODENBAUGH'S INC,...,ALLEN TX 75013-2764,0085,COLLIN,75013,9727273454,RAIC,N,RODENBAUGH'S INC,NaN,NaN
28030,Appliance Installation Contractor,116,HARRIS,RWB INSTALLATIONS,NaN,NaN,NaN,NaN,04152018,RWB INSTALLATIONS,...,LA PORTE TX 77571,0201,HARRIS,77571,7134774700,RAIC,N,RWB INSTALLATIONS,NaN,NaN
28031,Appliance Installation Contractor,118,DALLAS,D V S - DRYER VENTING SERVICES,NaN,NaN,NaN,NaN,04162018,D V S - DRYER VENTING SERVICES,...,PLANO TX 75023,0085,COLLIN,75023,2148020600,RAIC,N,D V S - DRYER VENTING SERVICES,NaN,NaN
28032,Appliance Installation Contractor,120,COLORADO,COLUMBUS TELEVISION CENTER INC,NaN,NaN,NaN,NaN,04172018,COLUMBUS TELEVISION CENTER INC,...,COLUMBUS TX 78934-2216,0089,COLORADO,78934,9797326054,RAIC,N,COLUMBUS TELEVISION CENTER INC,NaN,NaN
28033,Appliance Installation Contractor,122,WOOD,KIMMEN INSTALLATION,NaN,NaN,NaN,NaN,12212017,KIMMEN INSTALLATION,...,WINNSBORO TX 75494,0499,WOOD,75494,9036130236,RAIC,N,KIMMEN INSTALLATION,NaN,NaN
28034,Appliance Installation Contractor,123,BOWIE,SEARS ROEBUCK AND CO,NaN,NaN,NaN,NaN,04182018,SEARS ROEBUCK AND CO,...,HOFFMAN ESTATES IL 60179,0999,OUT OF STATE,60179,9037947327,RAIC,N,SEARS ROEBUCK AND CO,NaN,NaN
28035,Appliance Installation Contractor,125,DALLAS,INTRASTATE SALES ENTERPRISES INC,NaN,NaN,NaN,NaN,04282016,INTRASTATE SALES ENTERPRISES INC,...,DALLAS TX 75229-4730,0113,DALLAS,75229,2143576879,RAIC,N,INTRASTATE SALES ENTERPRISES INC,NaN,NaN
28036,Appliance Installation Contractor,128,MONTGOMERY,MR HANDYMAN OF THE WOODLANDS,NaN,NaN,NaN,NaN,05172017,MR HANDYMAN OF THE WOODLANDS,...,SPRING TX 77382,0339,MONTGOMERY,77382,2812962700,RAIC,N,MR HANDYMAN OF THE WOODLANDS,NaN,NaN
28037,Appliance Installation Contractor,129,PALO PINTO,DOSHIER APPL INC DBA DOSHIER APPL REPAIR,NaN,NaN,NaN,NaN,10262017,DOSHIER APPL INC DBA DOSHIER APPL REPAIR,...,MINERAL WELLS TX 76067,0363,PALO PINTO,76067,9403255555,RAIC,N,DOSHIER APPL INC DBA DOSHIER APPL REPAIR,NaN,NaN
28038,Appliance Installation Contractor,131,GALVESTON,KELM HOME SERVICES,NaN,NaN,NaN,NaN,07162016,KELM HOME SERVICES,...,SANTA FE TX 77517,0167,GALVESTON,77517,4093169834,RAIC,N,KELM HOME SERVICES,NaN,NaN
28039,Appliance Installation Contractor,132,TOM GREEN,TOM'S APPLIANCE INSTALLATIONS,NaN,NaN,NaN,NaN,05242017,TOM'S APPLIANCE INSTALLATIONS,...,SAN ANGELO TX 76904-6001,0451,TOM GREEN,76904,3256563668,RAIC,N,TOM'S APPLIANCE INSTALLATIONS,NaN,NaN
28040,Appliance Installation Contractor,134,FRANKLIN,MJ FEAGLEY,NaN,NaN,NaN,NaN,05272017,MJ FEAGLEY,...,SCROGGINS TX 75480,0159,FRANKLIN,75480,9038603176,RAIC,N,MJ FEAGLEY,NaN,NaN
28041,Appliance Installation Contractor,135,ROCKWALL,SIMPLE RESOLUTIONS,NaN,NaN,NaN,NaN,01282018,SIMPLE RESOLUTIONS,...,ROYSE CITY TX 75189,0397,ROCKWALL,75189,2144503323,RAIC,N,SIMPLE RESOLUTIONS,NaN,NaN
28042,Appliance Installation Contractor,142,EL PASO,SOBELLAS APPLIANCE LLC,NaN,NaN,NaN,NaN,07292017,SOBELLAS APPLIANCE LLC,...,EL PASO TX 79932,0141,EL PASO,79932,9155852811,RAIC,N,SOBELLAS APPLIANCE LLC,NaN,NaN
28043,Appliance Installation Contractor,143,RANDALL,J & S INDUSTRIAL & MECHANICAL LP,NaN,NaN,NaN,NaN,08012017,J & S INDUSTRIAL & MECHANICAL LP,...,AMARILLO TX 79118,0381,RANDALL,79118,8066220990,RAIC,N,J & S INDUSTRIAL & MECHANICAL LP,NaN,NaN
28044,Appliance Installation Contractor,149,SMITH,EAST TEXAS APPLIANCE SERVICE,NaN,NaN,NaN,NaN,11142017,EAST TEXAS APPLIANCE SERVICE,...,TYLER TX 75703-5301,0423,SMITH,75703,9035818200,RAIC,N,EAST TEXAS APPLIANCE SERVICE,NaN,NaN
28045,Appliance Installation Contractor,150,LUBBOCK,CAPROCK APPLIANCE REPAIR,NaN,NaN,NaN,NaN,11142017,CAPROCK APPLIANCE REPAIR,...,LUBBOCK TX 79410,0303,LUBBOCK,79410,8067840744,RAIC,N,CAPROCK APPLIANCE REPAIR,NaN,NaN
28046,Appliance Installation Contractor,153,HARRIS,KIVA KITCHEN/BATH MCNAIRS APPLIANCE INC,NaN,NaN,NaN,NaN,03252017,KIVA KITCHEN/BATH MCNAIRS APPLIANCE INC,...,AUSTIN TX 78758-7659,0453,TRAVIS,78758,5124544526,RAIC,N,KIVA KITCHEN/BATH MCNAIRS APPLIANCE INC,NaN,NaN
28047,Appliance Installation Contractor,155,MONTGOMERY,TOMMY'S APPLIANCE INSTALLATIONS LLC,NaN,NaN,NaN,NaN,03172017,TOMMY'S APPLIANCE INSTALLATIONS LLC,...,CONROE TX 77302,0339,MONTGOMERY,77302,9364463250,RAIC,N,TOMMY'S APPLIANCE INSTALLATIONS LLC,NaN,NaN
28048,Appliance Installation Contractor,156,BELL,TOLLY'S AIR CONDITIONING & REFRIGERATION,NaN,NaN,NaN,NaN,03022018,TOLLY'S AIR CONDITIONING & REFRIGERATION,...,KILLEEN TX 76549,0027,BELL,76549,2545190714,RAIC,N,TOLLY'S AIR CONDITIONING & REFRIGERATION,NaN,NaN
28049,Appliance Installation Contractor,160,WISE,COPLEN PLUMBING & INSTALLATIONS,NaN,NaN,NaN,NaN,09182017,COPLEN PLUMBING & INSTALLATIONS,...,BOYD TX 76023-0181,0497,WISE,76023,8175599185,RAIC,N,COPLEN PLUMBING & INSTALLATIONS,NaN,NaN
28050,Appliance Installation Contractor,161,TRAVIS,DARYL FLOOD LOGISTICS INC.,NaN,NaN,NaN,NaN,05112017,DARYL FLOOD LOGISTICS INC.,...,AUSTIN TX 78728-3953,0453,TRAVIS,78728,5126703777,RAIC,N,DARYL FLOOD LOGISTICS INC.,NaN,NaN
28051,Appliance Installation Contractor,162,TARRANT,SOLTHERMA INC,NaN,NaN,NaN,NaN,07082017,SOLTHERMA INC,...,HASLET TX 76052,0439,TARRANT,76052,8174272112,RAIC,N,SOLTHERMA INC,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590356,Used Auto Parts Recycler,1486,DALLAS,LKQ AUTO PARTS OF NORTH TEXAS,NaN,NaN,NaN,NaN,11022017,LKQ AUTO PARTS OF NORTH TEXAS,...,NEW BRAUNFELS TX 78130-3590,0091,COMAL,78130,8307433091,RECYCLER,N,LKQ AUTO PARTS OF NORTH TEXAS,NaN,NaN
590357,Used Auto Parts Recycler,1487,EL PASO,ANDRES AUTO SALE,NaN,NaN,NaN,NaN,11022017,ANDRES AUTO SALE,...,EL PASO TX 79938-7205,0141,EL PASO,79938,9153037448,RECYCLER,N,ANDRES AUTO SALE,NaN,NaN
590358,Used Auto Parts Recycler,1488,DALLAS,YOURFORD/TEXAS AUTO RECYCLERS,NaN,NaN,NaN,NaN,11082017,YOURFORD/TEXAS AUTO RECYCLERS,...,GRAND PRAIRIE TX 75051,0113,DALLAS,75051,9722633303,RECYCLER,N,YOURFORD/TEXAS AUTO RECYCLERS,NaN,NaN
590359,Used Auto Parts Recycler,1489,HARRIS,B & B RECYCLE CENTER,NaN,NaN,NaN,NaN,11142017,B & B RECYCLE CENTER,...,HOUSTON TX 77074-1300,0201,HARRIS,77074,7139816272,RECYCLER,N,B & B RECYCLE CENTER,NaN,NaN
590361,Used Auto Parts Recycler,1490,WEBB,CAVAZOS AUTO SALES INC,NaN,NaN,NaN,NaN,11152017,CAVAZOS AUTO SALES INC,...,LAREDO TX 78040-3749,0479,WEBB,78040,9567274123,RECYCLER,N,CAVAZOS AUTO SALES INC,NaN,NaN
590363,Used Auto Parts Recycler,1491,CORYELL,D & R PICK N PULL LLC,NaN,NaN,NaN,NaN,11182017,D & R PICK N PULL LLC,...,COPPERAS COVE TX 76522-3859,0099,CORYELL,76522,2542450526,RECYCLER,N,D & R PICK N PULL LLC,NaN,NaN
590364,Used Auto Parts Recycler,1492,HARRIS,DIXIE USED AUTO PARTS,NaN,NaN,NaN,NaN,11222017,DIXIE USED AUTO PARTS,...,NEW CANEY TX 77357,0339,MONTGOMERY,77357,2816893111,RECYCLER,N,DIXIE USED AUTO PARTS,NaN,NaN
590366,Used Auto Parts Recycler,1493,KAUFMAN,B&L TRUCK AND EQUIPMENT SALES,NaN,NaN,NaN,NaN,11282017,B&L TRUCK AND EQUIPMENT SALES,...,KEMP TX 75143,0257,KAUFMAN,75143,9723747036,RECYCLER,N,B&L TRUCK AND EQUIPMENT SALES,NaN,NaN
590367,Used Auto Parts Recycler,1494,WEBB,YONKE MONTERREY LLC,NaN,NaN,NaN,NaN,11302017,YONKE MONTERREY LLC,...,LAREDO TX 78043,0479,WEBB,78043,9567299333,RECYCLER,N,YONKE MONTERREY LLC,NaN,NaN
590369,Used Auto Parts Recycler,1495,TARRANT,KTS INVESTMENTS LLC,NaN,NaN,NaN,NaN,12052017,KTS INVESTMENTS LLC,...,FORT WORTH TX 76117,0439,TARRANT,76117,8178316316,RECYCLER,N,KTS INVESTMENTS LLC,NaN,NaN
590371,Used Auto Parts Recycler,1497,BEXAR,PRIMARY OPPURTUNITY GROUP LLC,NaN,NaN,NaN,NaN,12152017,PRIMARY OPPURTUNITY GROUP LLC,...,SAN ANTONIO TX 78211-1920,0029,BEXAR,78211,2103991648,RECYCLER,N,PRIMARY OPPURTUNITY GROUP LLC,NaN,NaN
590373,Used Auto Parts Recycler,1498,FORT BEND,ALPINE USED AUTO PARTS,NaN,NaN,NaN,NaN,12162017,ALPINE USED AUTO PARTS,...,STAFFORD TX 77477,0157,FORT BEND,77477,2812610606,RECYCLER,N,ALPINE USED AUTO PARTS,NaN,NaN
590375,Used Auto Parts Recycler,1499,DALLAS,AAA AUTO SALVAGE & PARTS,NaN,NaN,NaN,NaN,12202017,AAA AUTO SALVAGE & PARTS,...,HUBBARD TX 76648-2451,0217,HILL,76648,4694412184,RECYCLER,N,AAA AUTO SALVAGE & PARTS,NaN,NaN
590377,Used Auto Parts Recycler,1500,CLAY,HENRIETTA AUTO SHOP LLC,NaN,NaN,NaN,NaN,12202017,HENRIETTA AUTO SHOP LLC,...,HENRIETTA TX 76365-3235,0077,CLAY,76365,9405384621,RECYCLER,N,HENRIETTA AUTO SHOP LLC,NaN,NaN
590379,Used Auto Parts Recycler,1501,HIDALGO,YESENIA A HINOJOSA,NaN,NaN,NaN,NaN,12212017,YESENIA A HINOJOSA,...,MCALLEN TX 78503,0215,HIDALGO,78503,9564510794,RECYCLER,N,YESENIA A HINOJOSA,NaN,NaN
590380,Used Auto Parts Recycler,1502,WEBB,BMW PARTS INC,NaN,NaN,NaN,NaN,12222017,BMW PARTS INC,...,LAREDO TX 78043-4899,0479,WEBB,78043,9567910977,RECYCLER,N,BMW PARTS INC,NaN,NaN
590382,Used Auto Parts Recycler,1503,HIDALGO,MARIA I COELLO DE MARTINEZ,NaN,NaN,NaN,NaN,12222017,MARIA I COELLO DE MARTINEZ,...,HIDALGO TX 78557-3873,0215,HIDALGO,78557,9565331827,RECYCLER,N,MARIA I COELLO DE MARTINEZ,NaN,NaN
590383,Used Auto Parts Recycler,1504,PARKER,REV ACTION TRUCK PARTS,NaN,NaN,NaN,NaN,12272017,REV ACTION TRUCK PARTS,...,SPRINGTOWN TX 76082-6915,0367,PARKER,76082,9407048687,RECYCLER,N,REV ACTION TRUCK PARTS,NaN,NaN
590384,Used Auto Parts Recycler,1505,HARRIS,WHITTS AUTO SALES LLC,NaN,NaN,NaN,NaN,01042018,WHITTS AUTO SALES LLC,...,HOUSTON TX 77077-3301,0201,HARRIS,77077,2815890334,RECYCLER,N,WHITTS AUTO SALES LLC,NaN,NaN
590386,Used Auto Parts Recycler,1506,ECTOR,MARTINEZ AUTOMOTIVE INC,NaN,NaN,NaN,NaN,01092018,MARTINEZ AUTOMOTIVE INC,...,ODESSA TX 79764-9005,0135,ECTOR,79764,4323850076,RECYCLER,N,MARTINEZ AUTOMOTIVE INC,NaN,NaN
590387,Used Auto Parts Recycler,1507,WEBB,PAISANO USED AUTO PARTS,NaN,NaN,NaN,NaN,01132018,PAISANO USED AUTO PARTS,...,LAREDO TX 78043,0479,WEBB,78043,9567448415,RECYCLER,N,PAISANO USED AUTO PARTS,NaN,NaN
590388,Used Auto Parts Recycler,1508,CAMERON,ANSELDA NIQUELINA,NaN,NaN,NaN,NaN,01182018,ANSELDA NIQUELINA,...,HARLINGEN TX 78552-6797,0061,CAMERON,78552,9564251335,RECYCLER,N,ANSELDA NIQUELINA,NaN,NaN
590389,Used Auto Parts Recycler,1509,CAMERON,JUAN A.DE LEON,NaN,NaN,NaN,NaN,01252018,JUAN A.DE LEON,...,OLMITO TX 78575-5216,0061,CAMERON,78575,9563508299,RECYCLER,N,JUAN A.DE LEON,NaN,NaN
590390,Used Auto Parts Recycler,1510,HIDALGO,J & MS PARTS LLC,NaN,NaN,NaN,NaN,02072018,J & MS PARTS LLC,...,MCALLEN TX 78503,0215,HIDALGO,78503,9568435171,RECYCLER,N,J & MS PARTS LLC,NaN,NaN
590391,Used Auto Parts Recycler,1511,BELL,SNYDER'S,NaN,NaN,NaN,NaN,02072018,SNYDER'S,...,SAN ANTONIO TX 78219,0029,BEXAR,78219,2103266220,RECYCLER,N,SNYDER'S,NaN,NaN
590394,Used Auto Parts Recycler,1513,BEXAR,R & D PARTS INC.,NaN,NaN,NaN,NaN,02162018,R & D PARTS INC.,...,SAN ANTONIO TX 78211,0029,BEXAR,78211,2106232000,RECYCLER,N,R & D PARTS INC.,NaN,NaN
590396,Used Auto Parts Recycler,1514,DALLAS,DFW AUTO & PARTS SALES,NaN,NaN,NaN,NaN,02242018,DFW AUTO & PARTS SALES,...,HALTOM CITY TX 76117,0439,TARRANT,76117,8174399281,RECYCLER,N,DFW AUTO & PARTS SALES,NaN,NaN
590398,Used Auto Parts Recycler,1515,HARRIS,T&D BRADLEY AUTO SERVICE LLC,NaN,NaN,NaN,NaN,02242018,T&D BRADLEY AUTO SERVICE LLC,...,HOUSTON TX 77022-6106,0201,HARRIS,77022,8322096210,RECYCLER,N,T&D BRADLEY AUTO SERVICE LLC,NaN,NaN
590399,Used Auto Parts Recycler,1516,DALLAS,A & M AUTO PARTS,NaN,NaN,NaN,NaN,02282018,A & M AUTO PARTS,...,DALLAS TX 75216-4138,0113,DALLAS,75216,2143711500,RECYCLER,N,A & M AUTO PARTS,NaN,NaN
590400,Used Auto Parts Recycler,1517,TARRANT,STEVENS CORE SUPPLY INC,NaN,NaN,NaN,NaN,03012018,STEVENS CORE SUPPLY INC,...,SANSOM PARK TX 76114,0439,TARRANT,76114,8173329820,RECYCLER,N,STEVENS CORE SUPPLY INC,NaN,NaN

## 24. If it's a problem, you can fix it (if you'd like!)

Maybe you have another regular expression that works better with JUST these people? It really depends on how you've put together your previous regex!

If you'd like to use a separate regex for this group, you can use code like this:

`df.loc[df.FIRSTNAME.isnull(), 'FIRSTNAME'] = .....`

That will only set the `FIRSTNAME` for people where `FIRSTNAME` is null.

In [120]:
FIRSTNAME = df.loc[df.FIRSTNAME.isnull(), 'FIRSTNAME']

How many empty first names do we have now?

In [123]:
FIRSTNAME.isnull().value_counts()

True    81601
Name: FIRSTNAME, dtype: int64

My code before only worked for people with middle names, but now it got people without middle names, too. Looking much better!

## 25. Most popular first names?

In [125]:
df.first_name.value_counts()

NGUYEN             22286
TRAN                8137
LE                  5606
GARCIA              5574
MARTINEZ            4701
RODRIGUEZ           4626
HERNANDEZ           4390
PHAM                3997
GONZALEZ            3634
SMITH               3208
LOPEZ               2992
PEREZ               2583
WILLIAMS            2468
HUYNH               2436
RAMIREZ             2433
JOHNSON             2402
SANCHEZ             2381
FLORES              2164
GARZA               2145
JONES               2105
VO                  2009
BROWN               1908
PHAN                1787
TORRES              1749
DAVIS               1671
VU                  1575
TRUONG              1487
GOMEZ               1409
DANG                1359
HOANG               1349
                   ...
CRUZ CERDA             1
NARR                   1
JUBAILI                1
OONWALA                1
ROJAS-VAZQUEZ          1
MOFA                   1
AL KHATTAN             1
AVILA-REYES            1
ZIRION                 1
WIIKI                  1
BILLMIRE               1
MECHAM                 1
SKOCIBUSIC             1
GARCIA-OLVERA          1
CRAVY                  1
KURESKA                1
LOPEZ MATA             1
CLEMMER                1
MORENOVALLE            1
ROVATSOS               1
LOKHANDWALLA           1
GONZALEZ LEIVA         1
LATAPIE                1
BAYBO                  1
PATE                   1
TELAS                  1
PEREZ HERRERA          1
VADE                   1
HOI                    1
VASQUEZ SUTUJ          1
Name: first_name, Length: 73642, dtype: int64

## 26. Most popular first names for a Cosmetology Operator, Cosmetology Esthetician, Cosmetologist, and okay honestly anything that seems similar?

If you get an error about "cannot index vector containing NA / NaN values" remember `.fillna(False)` - if a row doesn't have a license, it doesn't give a `True`/`False`, so we force all of the empty rows to be `False`.

In [130]:
df.first_name = df.first_name.fillna(False)

In [ ]:
df..str.contains('stringname', na=True/False)

## 27. Most popular first names for anything involving electricity?

In [131]:
df

,LICTYPE,LICNUMBER,BIZCOUNTY,BIZNAME,BIZLINE1,BIZLINE2,BIZCITYSTATE,BIZTELEPHONE,EXPIRATION,OWNER,...,MAILCITYSTATE,MAILCOUNTYCODE,MAILCOUNTY,MAILZIP,TELEPHONE,LICSUBTYPE,CEFLAG,last_name,first_name,FIRSTNAME
0,Associate Auctioneer,7962,UPSHUR,"WILLIAMS, JON ANDRE",NaN,NaN,NaN,NaN,12292017,"WILLIAMS, JON ANDRE",...,KILGORE TX 75662,0183,GREGG,75662,9039187899,NaN,N,WILLIAMS,WILLIAMS,WILLIAMS
1,Associate Auctioneer,8406,WILSON,"GUEVARA, JUAN ANTONIO",NaN,NaN,NaN,NaN,09262017,"GUEVARA, JUAN ANTONIO",...,POTH TX 78147,0493,WILSON,78147,NaN,NaN,N,GUEVARA,GUEVARA,GUEVARA
2,Associate Auctioneer,10543,HARRIS,"BOWERS, JAMES BRISCOE II",NaN,NaN,NaN,NaN,11042017,"BOWERS, JAMES BRISCOE II",...,HOUSTON TX 77076-2027,0201,HARRIS,77076,7136445566,NaN,N,BOWERS,BOWERS,BOWERS
3,Associate Auctioneer,10642,BELL,"DEMSKY, JOHN EDWARD",NaN,NaN,NaN,NaN,02252018,"DEMSKY, JOHN EDWARD",...,BARTLETT TX 76511,0027,BELL,76511,2549852228,NaN,N,DEMSKY,DEMSKY,DEMSKY
4,Associate Auctioneer,15650,OUT OF STATE,"THOMPSON, RANDY D",NaN,NaN,NaN,NaN,05042017,"THOMPSON, RANDY D",...,RINGLING OK 73456,0999,OUT OF STATE,73456,5802765961,NaN,N,THOMPSON,THOMPSON,THOMPSON
5,Associate Auctioneer,15698,OUT OF STATE,"TUCKER, MONTE EARL",NaN,NaN,NaN,NaN,06162017,"TUCKER, MONTE EARL",...,SAYRE OK 73662-6080,0999,OUT OF STATE,73662,5802250269,NaN,N,TUCKER,TUCKER,TUCKER
6,Associate Auctioneer,15810,MILAM,"COOPER, THOMAS JAMES",NaN,NaN,NaN,NaN,03182017,"COOPER, THOMAS JAMES",...,ROSEBUD TX 76570,0145,FALLS,76570,2815078713,NaN,N,COOPER,COOPER,COOPER
7,Associate Auctioneer,15835,OUT OF STATE,"BLANKENSHIP, KERRY NEIL",NaN,NaN,NaN,NaN,05042017,"BLANKENSHIP, KERRY NEIL",...,RINGLING OK 73456-2014,0999,OUT OF STATE,73456,5802765961,NaN,N,BLANKENSHIP,BLANKENSHIP,BLANKENSHIP
8,Associate Auctioneer,16784,OUT OF STATE,"DAWES, NICHOLAS MORGAN",NaN,NaN,NaN,NaN,10192017,"DAWES, NICHOLAS MORGAN",...,DALLAS TX 75219,0113,DALLAS,75219,2144091137,NaN,N,DAWES,DAWES,DAWES
9,Associate Auctioneer,16893,LAMAR,"LESTER, TIMMY EUGENE",NaN,NaN,NaN,NaN,08192017,"LESTER, TIMMY EUGENE",...,CUNNINGHAM TX 75434,0277,LAMAR,75434,9037825759,NaN,N,LESTER,LESTER,LESTER
10,Associate Auctioneer,16969,NACOGDOCHES,"MANCILL, MARK DUANE",NaN,NaN,NaN,NaN,04212017,"MANCILL, MARK DUANE",...,LUFKIN TX 75904-4331,0005,ANGELINA,75904,9366749636,NaN,N,MANCILL,MANCILL,MANCILL
11,Associate Auctioneer,16990,BEXAR,"HUDDLESTON, SHAWN ALAN",NaN,NaN,NaN,NaN,02182017,"HUDDLESTON, SHAWN ALAN",...,SAN ANTONIO TX 78218,0029,BEXAR,78218,2106815425,NaN,N,HUDDLESTON,HUDDLESTON,HUDDLESTON
12,Associate Auctioneer,17072,ECTOR,"JORDAN, JAMES EUGENE",NaN,NaN,NaN,NaN,02182018,"JORDAN, JAMES EUGENE",...,ODESSA TX 79762,0135,ECTOR,79762,4322722266,NaN,N,JORDAN,JORDAN,JORDAN
13,Associate Auctioneer,17108,KAUFMAN,"IRWIN, MICHAEL RICHARD",NaN,NaN,NaN,NaN,02252017,"IRWIN, MICHAEL RICHARD",...,TERRELL TX 75160-7592,0257,KAUFMAN,75160,4695951384,NaN,N,IRWIN,IRWIN,IRWIN
14,Associate Auctioneer,17241,HOOD,"HALL, WESLEY RYON",NaN,NaN,NaN,NaN,01252018,"HALL, WESLEY RYON",...,COMANCHE TX 76442-7305,0093,COMANCHE,76442,3253565950,NaN,N,HALL,HALL,HALL
15,Associate Auctioneer,17242,ERATH,"JAMES, BACHUS ROSS",NaN,NaN,NaN,NaN,05042017,"JAMES, BACHUS ROSS",...,STEPHENVILLE TX 76401-2860,0143,ERATH,76401,2545928394,NaN,N,JAMES,JAMES,JAMES
16,Associate Auctioneer,17669,JOHNSON,"SIDAWI, JOSEPH JAMES",NaN,NaN,NaN,NaN,02082017,"SIDAWI, JOSEPH JAMES",...,JOSHUA TX 76058-6060,0251,JOHNSON,76058,8173200833,NaN,N,SIDAWI,SIDAWI,SIDAWI
17,Associate Auctioneer,17671,MILLS,"SMITH, DAVID JAMES",NaN,NaN,NaN,NaN,02082018,"SMITH, DAVID JAMES",...,GOLDTHWAITE TX 76844,0333,MILLS,76844,3259386750,NaN,N,SMITH,SMITH,SMITH
18,Associate Auctioneer,17672,BROWN,"FERGUSON, JACKIE LEE",NaN,NaN,NaN,NaN,02092018,"FERGUSON, JACKIE LEE",...,BANGS TX 76823,0049,BROWN,76823,3253727333,NaN,N,FERGUSON,FERGUSON,FERGUSON
19,Associate Auctioneer,17675,UPSHUR,"MCKINLEY, MATTHEW D",NaN,NaN,NaN,NaN,02182018,"MCKINLEY, MATTHEW D",...,GLADEWATER TX 75647-2415,0183,GREGG,75647,9038453830,NaN,N,MCKINLEY,MCKINLEY,MCKINLEY
20,Associate Auctioneer,17676,JOHNSON,"SOWELL, KALEN BRICE",NaN,NaN,NaN,NaN,02182018,"SOWELL, KALEN BRICE",...,CRESSON TX 76035,0221,HOOD,76035,8173821530,NaN,N,SOWELL,SOWELL,SOWELL
21,Associate Auctioneer,17679,ELLIS,"SEVIER, VIRGINIA A",NaN,NaN,NaN,NaN,02252018,"SEVIER, VIRGINIA A",...,WAXAHACHIE TX 75165,0139,ELLIS,75165,9726930572,NaN,N,SEVIER,SEVIER,SEVIER
22,Associate Auctioneer,17680,BELL,"SOMERVILLE, CAL W",NaN,NaN,NaN,NaN,02252017,"SOMERVILLE, CAL W",...,KILLEEN TX 76549-9049,0027,BELL,76549,2542893216,NaN,N,SOMERVILLE,SOMERVILLE,SOMERVILLE
23,Associate Auctioneer,17685,SAN SABA,"BARCLIFT, AUSTIN TYLER",NaN,NaN,NaN,NaN,03172018,"BARCLIFT, AUSTIN TYLER",...,BANGS TX 76823,0049,BROWN,76823,3253727333,NaN,N,BARCLIFT,BARCLIFT,BARCLIFT
24,Associate Auctioneer,17687,HARRIS,"FORD, PATRICIA NORA",NaN,NaN,NaN,NaN,03182017,"FORD, PATRICIA NORA",...,DEER PARK TX 77536-4704,0201,HARRIS,77536,2814797848,NaN,N,FORD,FORD,FORD
25,Associate Auctioneer,17689,DALLAM,"SCHAFER, TIMOTHY RYAN",NaN,NaN,NaN,NaN,04012017,"SCHAFER, TIMOTHY RYAN",...,DALHART TX 79022,0111,DALLAM,79022,8062446776,NaN,N,SCHAFER,SCHAFER,SCHAFER
26,Associate Auctioneer,17695,EL PASO,"MARTINEZ, BRANDY MARIE",NaN,NaN,NaN,NaN,04112017,"MARTINEZ, BRANDY MARIE",...,EL PASO TX 79912-2104,0141,EL PASO,79912,9153733887,NaN,N,MARTINEZ,MARTINEZ,MARTINEZ
27,Associate Auctioneer,17696,POTTER,"CLEMANS, ZACHARY LEE",NaN,NaN,NaN,NaN,04112017,"CLEMANS, ZACHARY LEE",...,AMARILLO TX 79124-2319,0375,POTTER,79124,8066833130,NaN,N,CLEMANS,CLEMANS,CLEMANS
28,Associate Auctioneer,17699,EL PASO,"MARTINEZ, ARTURO",NaN,NaN,NaN,NaN,04182017,"MARTINEZ, ARTURO",...,EL PASO TX 79912-2104,0141,EL PASO,79912,9153733887,NaN,N,MARTINEZ,MARTINEZ,MARTINEZ
29,Associate Auctioneer,17706,GRAYSON,"CARSON, DAVID WADE",NaN,NaN,NaN,NaN,04252017,"CARSON, DAVID WADE",...,HOWE TX 75459-4752,0181,GRAYSON,75459,9035325501,NaN,N,CARSON,CARSON,CARSON
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597785,Water Well Driller/Pump Installer,59847,MONTGOMERY,"SNUFFER, KENNETH DAVID",NaN,NaN,NaN,NaN,09162017,"SNUFFER, KENNETH DAVID",...,WILLIS TX 77378-4347,0339,MONTGOMERY,77378,9368566374,W,N,SNUFFER,SNUFFER,SNUFFER
597786,Water Well Driller/Pump Installer,59856,BEXAR,"MARTINEZ, JUAN R",NaN,NaN,NaN,NaN,09192017,"MARTINEZ, JUAN R",...,SAN ANTONIO TX 78240-1007,0029,BEXAR,78240,2106977114,M,N,MARTINEZ,MARTINEZ,MARTINEZ
597787,Water Well Driller/Pump Installer,59857,DEAF SMITH,"YOSTEN, BLAKE JOSEPH",NaN,NaN,NaN,NaN,09192017,"YOSTEN, BLAKE JOSEPH",...,HEREFORD TX 79045-3020,0117,DEAF SMITH,79045,8063646140,KP,N,YOSTEN,YOSTEN,YOSTEN
597788,Water Well Driller/Pump Installer,59858,MIDLAND,"CLICK, JAY MARCUS",NaN,NaN,NaN,NaN,09202017,"CLICK, JAY MARCUS",...,MIDLAND TX 79706-5112,0329,MIDLAND,79706,4326820703,W,N,CLICK,CLICK,CLICK
597789,Water Well Driller/Pump Installer,59862,OUT OF STATE,"PENSE, LARRY WAYNE",NaN,NaN,NaN,NaN,09222017,"PENSE, LARRY WAYNE",...,GLENPOOL OK 74033-3445,0999,OUT OF STATE,74033,9183223095,W,N,PENSE,PENSE,PENSE
597790,Water Well Driller/Pump Installer,59877,OUT OF STATE,"LARA, STEVEN D",NaN,NaN,NaN,NaN,10042017,"LARA, STEVEN D",...,PHOENIX AZ 85034-2208,0999,OUT OF STATE,85034,6024533252,M,N,LARA,LARA,LARA
597791,Water Well Driller/Pump Installer,59878,WHEELER,"SMITH, JACE E",NaN,NaN,NaN,NaN,10062017,"SMITH, JACE E",...,MOBEETIE TX 79061-4701,0483,WHEELER,79061,8068265975,KLPT,N,SMITH,SMITH,SMITH
597792,Water Well Driller/Pump Installer,59879,MADISON,"BINNICKER, RICHARD ALLEN",NaN,NaN,NaN,NaN,10062017,"BINNICKER, RICHARD ALLEN",...,MADISONVILLE TX 77864-1902,0313,MADISON,77864,9363485838,PW,N,BINNICKER,BINNICKER,BINNICKER
597793,Water Well Driller/Pump Installer,59886,TARRANT,"CHAVEZ, FRANCISCO JAVIER",NaN,NaN,NaN,NaN,10172017,"CHAVEZ, FRANCISCO JAVIER",...,FORT WORTH TX 76107-1411,0439,TARRANT,76107,8178770866,M,N,CHAVEZ,CHAVEZ,CHAVEZ
597794,Water Well Driller/Pump Installer,59887,DEAF SMITH,"GUERRERO, REY S",NaN,NaN,NaN,NaN,10172017,"GUERRERO, REY S",...,HEREFORD TX 79045-0871,0117,DEAF SMITH,79045,8063643109,KLPT,N,GUERRERO,GUERRERO,GUERRERO
597795,Water Well Driller/Pump Installer,59889,BURNET,"SAVAGE, CROCKETT NATHANIEL",NaN,NaN,NaN,NaN,10192017,"SAVAGE, CROCKETT NATHANIEL",...,MARBLE FALLS TX 78654-7385,0053,BURNET,78654,8306932340,P,N,SAVAGE,SAVAGE,SAVAGE
597796,Water Well Driller/Pump Installer,59890,OUT OF STATE,"ADAMS, AARON J",NaN,NaN,NaN,NaN,10192017,"ADAMS, AARON J",...,PHOENIX AZ 85034-2208,0999,OUT OF STATE,85034,6024533252,M,N,ADAMS,ADAMS,ADAMS
597797,Water Well Driller/Pump Installer,59892,MIDLAND,"SCOTT, JAMES A",NaN,NaN,NaN,NaN,10312017,"SCOTT, JAMES A",...,MIDLAND TX 79701-4417,0329,MIDLAND,79701,4325578821,W,N,SCOTT,SCOTT,SCOTT
597798,Water Well Driller/Pump Installer,59896,BREWSTER,"HILL, RYAN WADE",NaN,NaN,NaN,NaN,11142017,"HILL, RYAN WADE",...,ALPINE TX 79830-1049,0043,BREWSTER,79830,4322942335,KLP,N,HILL,HILL,HILL
597799,Water Well Driller/Pump Installer,59901,HAYS,"THOMPSON, JARED W T",NaN,NaN,NaN,NaN,11222017,"THOMPSON, JARED W T",...,DRIPPING SPRINGS TX 78620-2477,0209,HAYS,78620,5128944221,KP,N,THOMPSON,THOMPSON,THOMPSON
597800,Water Well Driller/Pump Installer,59902,DENTON,"THOMAS, WESLEY WAYNE",NaN,NaN,NaN,NaN,11282017,"THOMAS, WESLEY WAYNE",...,BOWIE TX 76230-5969,0337,MONTAGUE,76230,9408726992,W,N,THOMAS,THOMAS,THOMAS
597801,Water Well Driller/Pump Installer,59904,BOSQUE,"JURGENSEN, JOSHUA MARK",NaN,NaN,NaN,NaN,11292017,"JURGENSEN, JOSHUA MARK",...,VALLEY MILLS TX 76689-2963,0035,BOSQUE,76689,2549326251,KPT,N,JURGENSEN,JURGENSEN,JURGENSEN
597802,Water Well Driller/Pump Installer,59905,HAYS,"MARSH, AARON ANDREW",NaN,NaN,NaN,NaN,12012017,"MARSH, AARON ANDREW",...,DRIPPING SPRINGS TX 78620-4097,0209,HAYS,78620,5128584375,P,N,MARSH,MARSH,MARSH
597803,Water Well Driller/Pump Installer,59907,UVALDE,"KILLOUGH, BRUCE WAYNE",NaN,NaN,NaN,NaN,12052017,"KILLOUGH, BRUCE WAYNE",...,UTOPIA TX 78884-2602,0463,UVALDE,78884,8309663456,KP,N,KILLOUGH,KILLOUGH,KILLOUGH
597804,Water Well Driller/Pump Installer,59908,COLLINGSWORTH,"FAULKS, CARSON SLADE",NaN,NaN,NaN,NaN,12062017,"FAULKS, CARSON SLADE",...,QUAIL TX 79251-4126,0087,COLLINGSWORTH,79251,8068981609,KLPTW,N,FAULKS,FAULKS,FAULKS
597805,Water Well Driller/Pump Installer,59911,ATASCOSA,"ATKINS, BRANDON BUCHANAN",NaN,NaN,NaN,NaN,12132017,"ATKINS, BRANDON BUCHANAN",...,PLEASANTON TX 78064-1733,0013,ATASCOSA,78064,8302812400,KPT,N,ATKINS,ATKINS,ATKINS
597806,Water Well Driller/Pump Installer,59912,OUT OF STATE,"WILLIAMS, MARC R",NaN,NaN,NaN,NaN,12152017,"WILLIAMS, MARC R",...,PHOENIX AZ 85034-2208,0999,OUT OF STATE,85034,6024533252,M,N,WILLIAMS,WILLIAMS,WILLIAMS
597807,Water Well Driller/Pump Installer,59913,LIMESTONE,"WINSTEAD, CLINTON WADE",NaN,NaN,NaN,NaN,12262017,"WINSTEAD, CLINTON WADE",...,GROESBECK TX 76642-2304,0293,LIMESTONE,76642,2547293762,W,N,WINSTEAD,WINSTEAD,WINSTEAD
597808,Water Well Driller/Pump Installer,59926,HENDERSON,"LILLEY, CLINTON",NaN,NaN,NaN,NaN,01132018,"LILLEY, CLINTON",...,ATHENS TX 75751-2236,0213,HENDERSON,75751,9036752353,KLP,N,LILLEY,LILLEY,LILLEY
597809,Water Well Driller/Pump Installer,59929,BOSQUE,"WOODS, JACOB R",NaN,NaN,NaN,NaN,01232018,"WOODS, JACOB R",...,VALLEY MILLS TX 76689-2963,0035,BOSQUE,76689,2549326251,P,N,WOODS,WOODS,WOODS
597810,Water Well Driller/Pump Installer,59930,TOM GREEN,"ABEL, JUSTIN C",NaN,NaN,NaN,NaN,01232018,"ABEL, JUSTIN C",...,SAN ANGELO TX 76901-9716,0451,TOM GREEN,76901,3259496607,KP,N,ABEL,ABEL,ABEL
597811,Water Well Driller/Pump Installer,59931,RUNNELS,"GRAY, MATTHEW BRYAN",NaN,NaN,NaN,NaN,01232018,"GRAY, MATTHEW BRYAN",...,ROWENA TX 76875-2608,0399,RUNNELS,76875,3254422331,KLPW,N,GRAY,GRAY,GRAY
597812,Water Well Driller/Pump Installer,59934,LAVACA,"MAYER, DAVID W",NaN,NaN,NaN,NaN,01272018,"MAYER, DAVID W",...,YOAKUM TX 77995-6786,0285,LAVACA,77995,3612933168,P,N,MAYER,MAYER,MAYER
597813,Water Well Driller/Pump Installer,59936,HOCKLEY,"FRIESEN, FRANCISCO FEHR",NaN,NaN,NaN,NaN,02132018,"FRIESEN, FRANCISCO FEHR",...,LEVELLAND TX 79336-9124,0219,HOCKLEY,79336,8065980508,W,N,FRIESEN,FRIESEN,FRIESEN
597814,Water Well Driller/Pump Installer,59941,WILSON,"BAUER, DAVID A",NaN,NaN,NaN,NaN,02162018,"BAUER, DAVID A",...,FLORESVILLE TX 78114-6076,0493,WILSON,78114,8303917338,W,N,BAUER,BAUER,BAUER

## 28. Can we be any more obnoxious in this assignment?

Not only are we going to detect gender from first names, but we're also going to use a library that has the terrible name of [sex machine](https://github.com/ferhatelmas/sexmachine/). Once upon a time there was Ruby package named sex machine and everyone was like "come on are you six years old? is this how we do things?" and the guy was like "you're completely right I'm renaming it to [gender detector](https://github.com/bmuller/gender_detector)" and the world was Nice and Good again. Apparently Python didn't get the message.

Except actually sexmachine doesn't work on Python 3 because it's from 300 BC so we're going to use a Python 3 fork called [gender guesser](https://pypi.python.org/pypi/gender-guesser/) (hooray!).

#### Use `pip` or `pip3` to install gender-guesser.

In [ ]:
!pip install gender-guesser

#### Test to see that it works

In [ ]:
import gender_guesser.detector as gender

detector = gender.Detector(case_sensitive=False)
detector.get_gender('David')

In [ ]:
detector.get_gender('Jose')

In [ ]:
detector.get_gender('Maria')

#### Use it on a dataframe

To use something fancy like that on a dataframe, you use `.apply`. Check it out:

In [ ]:
df['FIRSTNAME'].fillna('').apply(lambda name: detector.get_gender(name)).head()

## 29. Calculate the gender of everyone's first name and save it to a column

Confirm by see how many people of each gender we have

## 30. We like taking risks - get rid of ambiguity

* Combine the `mostly_female` into `female` 
* Combine the `mostly_male` into `male`
* Replace `andy` (androgynous) and `unknown` with `NaN`

you can get NaN not by making a string, but with `import numpy as np` and then using `np.nan`.

In [ ]:
import numpy as np

## 31. Do men or women have more licenses? What is the percentage of unknown genders?

## 32. What are the popular unknown- or ambiguous gender first names?

Yours might be different! Mine is a combination of actual ambiguity, cultural bias and dirty data.

## 31. What are the most popular licenses for men? For women?

## 32. What is the gender breakdown for Property Tax Appraiser? How about anything involving Tow Trucks?

If you're in need, remember your good friend `.fillna(False)` to get rid of NaN values.

(By the way, what are those tow truck jobs?)

## 33. Graph them!

And let's **give them titles** so we know which is which.

## 34. Calcuate the gender bias for profession

I spent like an hour on this and then realized a super easy way to do it. Welcome to programming! I'll do this part for you.

In [ ]:
# So when you do .value_counts(), it gives you an index and a value
df[df['GENDER'] == 'male'].LICTYPE.value_counts().head()

We did `pd.concat` to combine dataframes, but you can also use it to combine series (like the results of `value_counts()`). If you give it a few `value_counts()` and give it some column names it'll make something real nice.

In [ ]:
# All of the values_counts() we will be combining
vc_series = [
    df[df['GENDER'] == 'male'].LICTYPE.value_counts(),
    df[df['GENDER'] == 'female'].LICTYPE.value_counts(),
    df[df['GENDER'].isnull()].LICTYPE.value_counts()
]
# You need axis=1 so it combines them as columns
gender_df = pd.concat(vc_series, axis=1)
gender_df.head()

In [ ]:
# Turn "A/C Contractor" etc into an actual column instead of an index
gender_df.reset_index(inplace=True)
gender_df.head()

In [ ]:
# Rename the columns appropriately
gender_df.columns = ["license", "male", "female", "unknown"]
# Clean up the NaN by replacing them with zeroes
gender_df.fillna(0, inplace=True)
gender_df.head()

## 35. Add new columns for total licenses, percent known (not percent unknown!), percent male (of known), percent female (of known)

And replace any `NaN`s with `0`.

## 35. What 10 licenses with more than 2,000 people and over 75% known has the most male owners? The most female?

## 36. Let's say you have to call a few people about being in a profession dominated by the other gender. What are their phone numbers?

This will involve doing some research in one dataframe, then the other one. I didn't put an answer here because I'm interested in what you come up with!

## PART FIVE: Violations

### 37. Read in **violations.csv** as `violations_df`, make sure it looks right

### 38. Combine with your original licenses dataset dataframe to get phone numbers and addresses for each violation. Check that it is 90 rows, 28 columns.

## 39. Find each violation involving a failure with records. Use a regular expression.

## 40. How much money was each fine? Use a regular expression and .str.extract (we talked about it before!)

Unfortunately large and helpful troubleshooting tip: `$` means "end of a line" in regex, so `.extract` isn't going to accept it as a dollar sign. You need to escape it by using `\$` instead.

## 41. Clean those results (no commas, no dollar signs, and it should be an integer) and save it to a new column called `fine`

`.replace` is for *entire cells*, you're interested in `.str.replace`, which treats each value like a string, not like a... pandas thing.

`.astype(int)` will convert it into an integer for you.

## 42. Which orders results in the top fines?

## 43. Are you still here???

I'm sure impressed.