# Medical Examiner Case Archives

Cook County (Chicago) medical examiner records, taken from [here](https://datacatalog.cookcountyil.gov/Public-Safety/Medical-Examiner-Case-Archive/cjeq-bs86) after discovery via [Data is Plural](https://tinyletter.com/data-is-plural).

## Do your importing/setup

In [1]:
import pandas as pd
%matplotlib inline

import re

%matplotlib inline

df= pd.read_csv("Medical_Examiner_Case_Archive.csv", na_values=[0, "Data missing"])

## Read in the data, check its row count and column types

In [2]:
df.shape

(22634, 20)

## Cleaning up your data

First you'll want to convert the `Race` and `Gender` columns from codes into actual text to make analysis easier.

### Gender codes

* `-1` - `Data missing`
* `0` - `Female`
* `1` - `Male`
* `2` - `Unknown`

### Race codes

* `-1` - `Data missing`
* `0` - `American Indian`
* `1` - `Asian`
* `2` - `Black`
* `3` - `Other`
* `4` - `Unknown`
* `5` - `White`

In [3]:
df.head()

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
0,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20468,NaN
1,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2110 W. 21ST PL #1,CHICAGO,-87.678845,41.853279,77827,"(41.8532787, -87.6788449)"
2,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
3,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64.0,Female,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.728177,41.957468,77823,"(41.9574677, -87.7281769)"
4,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61.0,Male,Black,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3947 W. LEXINGTON STREET,CHICAGO,-87.724739,41.871451,77822,"(41.8714515, -87.7247386)"

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

## What percent of the dataset is men, and what percent is women?

It should display as **Male** and **Female**, not as numbers.

In [4]:
df.Gender.value_counts() #percentage

Male       16158
Female      6363
Unknown       12
Name: Gender, dtype: int64

## Getting rid of "Data missing"

`Unknown` means that officially the gender or race is unknown, while `Data missing` means the record is incomplete. That means "Data missing" should have been `NaN`!

Go back to your `read_csv` many cells before and make it so that "Data missing" is automatically set as `NaN`.

- *Tip: Do not use `.replace` for this one!*
- *Tip: Look at the options for `read_csv`, there's something that lets you specify missing values*
- *Tip: It isn't `"Data missing"` - think about how you already replaced*
- *Tip: Be sure you're using an array when you tell it what the 'missing' options are*

### After you've done this, re-run all of the the previous cells and confirm that `"Data missing"` does not exist any more

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

## What is the most common race in the dataset? We want percentages.

We'll come back to this later, I'm just having you check the column for now.

In [5]:
df.Race.value_counts() #percentage

White         12490
Black          9366
Asian           342
Other           269
Unknown          28
Am. Indian       15
Name: Race, dtype: int64


## Do a `.value_counts()` on the `Opioid Related` column

In [6]:

df['Opioid Related'].value_counts()

True    3378
Name: Opioid Related, dtype: int64

## That's weird. Did everyone die from opioids? Try again, but including missing data.

In [7]:
df['Opioid Related'].value_counts(dropna=False)

NaN     19256
True     3378
Name: Opioid Related, dtype: int64

## Cleaning up True/False columns

For some reason in this dataset, the True/False columns are either `True` or `NaN`. `NaN` causes a lot of problems, I'd rather have it be false.

You can use [`fillna`](http://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.DataFrame.fillna.html) to fill in empty data - it's like `.replace` but for `NaN`.

### Replace all `NaN` values with `False` for the "Gun Related" and "Opioid Related" columns.

In [8]:
df['Opioid Related'] = df['Opioid Related'].fillna(value=False)

### Do another value counts on Opioid Related to make sure it has both True and False values

In [9]:
df['Opioid Related'].value_counts(dropna=False)

False    19256
True      3378
Name: Opioid Related, dtype: int64

# Back to analysis!

## What's the average age people were when they died?

In [10]:
df.Age.mean()

52.09132007233273

## Let's look at how the oldest people died

We're just going to browse. Read through how the **oldest 30 people died.**

In [11]:
df.sort_values('Age', ascending = False).head(30)

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
21142,ME2018-00494,01/11/2018 12:00:00 PM,01/24/2018 03:48:00 PM,106.0,Female,White,False,ACCIDENT,COMPLICATIONS OF A FALL,NaN,NaN,NaN,NaN,False,627 ORIOLE DR SYMPHONY NURSING HOME,STREAMWOOD,-88.166639,42.014994,61564,"(42.0149937, -88.1666392)"
17602,ME2017-02853,06/19/2017 08:15:00 PM,06/20/2017 10:08:00 PM,106.0,Female,White,False,NaN,ACUTE MYOCARDIAL INFARCTION,NaN,NaN,"FRACTURE OF FEMUR DUE TO FALL, HYPERTENSIVE AN...",NaN,False,8021 W 151st St,ORLAND PARK,-87.815531,41.615936,59223,"(41.6159359, -87.8155315)"
12106,ME2016-03535,07/20/2016 06:30:00 PM,07/20/2016 06:58:00 PM,105.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,126 DIVERSEY,NORTHLAKE,-87.908596,41.929038,57807,"(41.9290381, -87.9085962)"
9376,ME2016-00729,02/10/2016 11:53:00 PM,02/11/2016 12:25:00 AM,103.0,Female,White,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,1933 Arklow Street,SCHAUMBURG,-88.127944,42.025985,61674,"(42.0259851, -88.1279436)"
8653,ME2015-05648,12/28/2015 09:30:00 PM,12/28/2015 09:59:00 PM,103.0,Female,Black,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,NaN,NaN,False,"4206 W. POTOMAC, 1ST FLOOR",CHICAGO,-87.731690,41.904602,68911,"(41.904602, -87.7316903)"
4942,ME2015-01809,04/26/2015 03:30:00 PM,05/03/2015 03:06:00 PM,103.0,Female,White,False,ACCIDENT,COMPLICATIONS OF FALL,NaN,NaN,NaN,NaN,False,7 WILLOW COURT,COUNTRYSIDE,-87.860635,41.783044,56056,"(41.7830443, -87.8606347)"
14697,ME2016-06170,12/23/2016 10:30:00 PM,12/24/2016 02:00:00 AM,101.0,Female,Black,False,ACCIDENT,INHALATION OF PRODUCTS OF COMBUSTION,NaN,NaN,NaN,NaN,False,2000 S. 9TH,MAYWOOD,-87.843632,41.867806,62018,"(41.8678057, -87.8436321)"
8656,ME2015-05651,12/30/2015 04:30:00 PM,12/30/2015 04:50:00 PM,101.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,"733 W. 19TH STREET, GROUND APT",CHICAGO,-87.646042,41.856563,67437,"(41.8565629, -87.646042)"
5621,ME2015-02517,06/17/2015 10:30:00 AM,06/17/2015 10:50:00 AM,101.0,Female,White,False,NATURAL,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,NaN,NaN,NaN,NaN,False,420 N. WOLF RD. #229,NORTHLAKE,-87.905080,41.915730,58002,"(41.9157304, -87.9050796)"
11558,ME2016-02979,06/12/2016 08:30:00 AM,06/17/2016 07:50:00 AM,101.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT FEMORAL NECK FRACTURE,NaN,NaN,"DEMENTIA, HYPERTENSION, ANEMIA",NaN,False,1270 FRANCISCAN DRIVE - MOTHER TERESA NH,LEMONT,-87.972860,41.679977,63499,"(41.6799768, -87.9728597)"
13498,ME2016-04942,10/14/2016 04:00:00 PM,10/14/2016 04:21:00 PM,101.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,"2626 NORTH LAKEVIEW, UNIT 3008",CHICAGO,-87.639827,41.930351,67009,"(41.9303508, -87.6398266)"
9904,ME2016-01281,03/13/2016 04:30:00 PM,03/13/2016 04:57:00 PM,101.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,"3409 SOUTH ASHLAND, 1ST FLOOR REAR APT.",CHICAGO,-87.665314,41.831971,65188,"(41.831971, -87.6653139)"
4239,ME2015-01074,03/12/2015 10:00:00 AM,03/12/2015 04:30:00 PM,100.0,Female,White,False,ACCIDENT,FRACTURE OF HIP,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, CHRONIC R...",NaN,False,640 BERGANDY COURT,ELK GROVE VILLAGE,NaN,NaN,60570,NaN
5817,ME2015-02723,06/29/2015 11:00:00 AM,06/29/2015 11:46:00 AM,100.0,Male,White,False,NATURAL,ASCVD,NaN,NaN,NaN,NaN,False,1316 CONCORD LN,SCHAUMBURG,-88.112903,42.012324,62245,"(42.0123239, -88.1129032)"
7898,ME2015-04864,10/15/2015 07:41:00 PM,11/10/2015 10:30:00 PM,100.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIGHT HIP FRACTURE,NaN,NaN,"ATRIAL FIBRILLATION, DEMENTIA",NaN,False,336 S Windsor,ARLINGTON HEIGHTS,-87.964208,42.077622,60002,"(42.0776216, -87.9642079)"
4015,ME2015-00842,02/16/2015 08:34:00 PM,02/26/2015 06:45:00 PM,100.0,Female,White,False,ACCIDENT,COMPLICATIONS FOLLOWING LEFT HIP FRACTURE,NaN,NaN,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,NaN,False,800 West Central Road,ARLINGTON HEIGHTS,-87.992553,42.068009,60130,"(42.0680087, -87.9925527)"
2610,ME2014-01556,11/19/2014 10:41:00 AM,11/20/2014 08:35:00 PM,100.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIGHT FEMORAL NECK FRACTURE,NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,False,6631 N. Milwaukee,NILES,-87.791694,42.002101,77212,"(42.0021012, -87.7916938)"
8780,ME2016-00111,12/28/2015 11:11:00 PM,01/03/2016 11:40:00 AM,100.0,Female,White,False,ACCIDENT,COMPLICATIONS OF FRACTURE OF FEMUR,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,False,5333 N SHERIDAN RD #23J,CHICAGO,-87.654376,41.979434,74168,"(41.9794337, -87.6543755)"
798,ME2018-01708,04/08/2018 03:03:00 PM,04/08/2018 03:12:00 PM,100.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,4035 North Leclaire,CHICAGO,-87.754434,41.954423,73911,"(41.9544229, -87.7544336)"
3985,ME2015-00812,02/19/2015 12:00:00 PM,02/25/2015 06:44:00 AM,100.0,Female,White,False,ACCIDENT,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,NaN,NaN,"FRACTURE OF RIGTH TIBIA, ALZHEIMER'S DISEASE,...",NaN,False,"Lexington Hospice, 815 E Irving Park Rd",STREAMWOOD,NaN,NaN,61176,NaN
17789,ME2017-03051,07/02/2017 03:45:00 PM,07/02/2017 05:40:00 PM,100.0,Female,White,False,ACCIDENT,ASPHYXIA,NaN,NaN,ORGANIC CARDIOVASCULAR DISEASE,NaN,False,"6840 N. SACRAMENTO AVENUE, ROOM# 414B",CHICAGO,NaN,NaN,75141,NaN
17142,ME2017-02376,05/24/2017 04:30:00 PM,05/24/2017 05:47:00 PM,100.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,WEST 36TH ST AND HERMITAGE AVE,CHICAGO,-87.669137,41.828642,64638,"(41.8286417, -87.6691374)"
9859,ME2016-01233,02/28/2016 10:25:00 AM,03/10/2016 03:20:00 AM,100.0,Female,Asian,False,ACCIDENT,SUBDURAL HEMORRHAGE,NaN,NaN,"ATRIAL FIBRILLATION, HYPERTENSIVE AND ATHEROSC...",NaN,False,1045 SOUTH GROVE AVENUE,OAK PARK,-87.795475,41.868916,63202,"(41.8689159, -87.7954748)"
13696,ME2016-05143,09/30/2016 12:00:00 PM,10/28/2016 04:08:00 AM,100.0,Female,Black,False,ACCIDENT,COMPLICATIONS OF BILATERAL FEMUR FRACTURES,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,False,Citadel NH 3701 W 183rd,HAZEL CREST,-87.706555,41.556419,63741,"(41.5564191, -87.7065553)"
10335,ME2016-01724,04/08/2016 06:00:00 AM,04/08/2016 06:47:00 AM,100.0,Male,White,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,2705 NORTH MOBILE,CHICAGO,-87.782931,41.929431,73899,"(41.9294315, -87.7829312)"
14044,ME2016-05503,11/16/2016 09:55:00 AM,11/16/2016 10:00:00 AM,100.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,4900 W. POTOMAC 1ST FLR.,CHICAGO,-87.748635,41.904362,76597,"(41.904362, -87.7486353)"
17007,ME2017-02248,05/17/2017 12:22:00 PM,05/17/2017 12:50:00 PM,99.0,Female,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,"820 W..Belleplaine, Apt. 303",CHICAGO,-87.650743,41.957547,67150,"(41.9575473, -87.6507429)"
914,ME2014-01729,12/03/2014 09:30:00 AM,12/03/2014 10:16:00 AM,99.0,Female,Black,False,ACCIDENT,CORONARY ATHEROSCLEROSIS,NaN,NaN,HYPOTHERMIA DUE TO COLD EXPOSURE,NaN,False,8726 S Parnell,CHICAGO,-87.637785,41.735119,69071,"(41.7351193, -87.6377846)"
3674,ME2015-00491,01/28/2015 05:00:00 PM,01/28/2015 05:27:00 PM,99.0,Female,White,False,ACCIDENT,PROBABLE ASPHYXIATION,NaN,NaN,ALZHEIMER'S DEMENTIA,NaN,False,"3121 NORTH SHERIDAN ROAD, UNIT 614",CHICAGO,-87.639195,41.938454,75717,"(41.9384542, -87.6391953)"
12048,ME2016-03477,07/16/2016 06:24:00 PM,07/16/2016 06:42:00 PM,99.0,Female,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,710 S. INDEPENDENCE BLVD APT 2,CHICAGO,-87.720663,41.872186,70434,"(41.8721858, -87.7206633)"

## Seems like a lot of problems with fractures

### What's the median age of someone dying from a cause that involves a fracture?

Are fractures especially dangerous for the elderly?

- *Tip: Filter for a cause that involves a fracture, then take the median age*
- *Tip: If you get a "cannot index NA values" error, the problem is it's trying to search `NaN` values and doesn't know what to do with them. You need to tell pandas to count `NaN` as false by setting another option - it isn't `NaN=False`, but it's close!*

In [12]:
fracture = df[df['Primary Cause'].str.contains('FRACTURE').fillna(value=False)]
fracture

fracture.median()

C:\Users\Shaleen\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\lib\nanfunctions.py:1076: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

Age                  86.000000
Latino                0.000000
Opioid Related        0.000000
longitude           -87.800225
latitude             41.924898
OBJECTID          60827.500000
dtype: float64

### To get a "compared to what?", what's the median age of _anyone_ dying an accidental death?

In [13]:
accident = df[df['Manner of Death'].str.contains('ACCIDENT').fillna(value=False)]
accident
accident.mean()

Age                  52.470464
Latino                0.091648
Opioid Related        0.427429
longitude           -87.734993
latitude             41.850005
OBJECTID          66110.189721
dtype: float64

### What's the median age of each manner of death?

It looks like different kinds of death might happen to different ages of people. Let's investigate that further.

In [14]:
df['Manner of Death'].value_counts()

NATURAL         9220
ACCIDENT        7627
HOMICIDE        2839
SUICIDE         1711
UNDETERMINED     502
PENDING          459
Name: Manner of Death, dtype: int64

In [15]:
natural = df[df['Manner of Death'].str.contains('NATURAL').fillna(value=False)]
natural.median()

Age                  61.000000
Latino                0.000000
Opioid Related        0.000000
longitude           -87.695988
latitude             41.858385
OBJECTID          67794.500000
dtype: float64

In [16]:
accident = df[df['Manner of Death'].str.contains('ACCIDENT').fillna(value=False)]
accident.median()

Age                  51.000000
Latino                0.000000
Opioid Related        0.000000
longitude           -87.715975
latitude             41.871021
OBJECTID          65552.000000
dtype: float64

In [17]:
homicide = df[df['Manner of Death'].str.contains('HOMICIDE').fillna(value=False)]
homicide.median()

Age                  26.000000
Latino                0.000000
Opioid Related        0.000000
longitude           -87.671368
latitude             41.801264
OBJECTID          68575.000000
dtype: float64

In [18]:
suicide = df[df['Manner of Death'].str.contains('SUICIDE').fillna(value=False)]
suicide.median()

Age                  45.000000
Latino                0.000000
Opioid Related        0.000000
longitude           -87.728066
latitude             41.892251
OBJECTID          64436.000000
dtype: float64

### Who is the oldest homicide victim?

It looks like homicide is for young people, so maybe we'll find an interesting outlier?

In [19]:
homicide.sort_values('Age', ascending = False).head(1)

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
3702,ME2015-00519,02/03/2015 08:21:00 AM,02/04/2015 08:34:00 AM,98.0,Female,Black,False,HOMICIDE,MORPHINE AND HYDROCODONE TOXICITY,NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,True,16300 louis Ave,SOUTH HOLLAND,-87.609278,41.598109,64404,"(41.5981086, -87.6092784)"

## Investigating toxicity-related homicides

She was old, and was purposefully overdosed on morphine and hydrocodone. Might have been euthenasia? Let's find similar cases.

### Find every homicide where the primary cause of death is some sort of toxicity

Toxicity can just overdose. You should have **ten rows**.

- *Tip: If you're doing this as one statement, make sure you use your parentheses correctly. If you leave them out, you'll have zero rows*
- *Tip: You could make a homicides-only dataframe if you wanted to*

In [20]:
df[df['Manner of Death'].str.contains('HOMICIDE').fillna(value=False) & df['Primary Cause'].str.contains('TOXICITY').fillna(value=False)]

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
3702,ME2015-00519,02/03/2015 08:21:00 AM,02/04/2015 08:34:00 AM,98.0,Female,Black,False,HOMICIDE,MORPHINE AND HYDROCODONE TOXICITY,NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,True,16300 louis Ave,SOUTH HOLLAND,-87.609278,41.598109,64404,"(41.5981086, -87.6092784)"
5395,ME2015-02286,05/27/2015 03:15:00 PM,06/03/2015 07:25:00 PM,28.0,Female,White,False,HOMICIDE,"COMPLICATIONS OF AMITRIPTYLINE AND METABOLITE,...",NaN,NaN,NaN,NaN,False,1102 S. Springinsguth Rd. #1D,SCHAUMBURG,-88.119741,42.005376,60663,"(42.005376, -88.1197414)"
6144,ME2015-03058,07/18/2015 07:00:00 AM,07/19/2015 02:05:00 AM,10.0,Male,Black,False,HOMICIDE,CARBON MONOXIDE TOXICITY,INCENDIARY HOUSE FIRE,NaN,NaN,NaN,False,8327 S. DREXEL,CHICAGO,-87.602328,41.743167,68218,"(41.7431675, -87.6023283)"
6764,ME2015-03692,08/29/2015 09:41:00 AM,08/29/2015 01:00:00 PM,28.0,Male,White,True,HOMICIDE,CARBON MONOXIDE TOXICITY,HOUSE FIRE,NaN,NaN,NaN,False,5209 S Lorel Avenue,CHICAGO,-87.755913,41.798035,72663,"(41.7980351, -87.7559129)"
6765,ME2015-03693,08/29/2015 09:41:00 AM,08/29/2015 01:00:00 PM,63.0,Male,Other,False,HOMICIDE,CARBON MONOXIDE TOXICITY,HOUSE FIRE,NaN,"ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE, ACUTE...",NaN,False,5205 S. Lorel,CHICAGO,-87.756075,41.798102,73036,"(41.7981017, -87.7560751)"
7612,ME2015-04564,10/22/2015 10:39:00 AM,10/22/2015 11:05:00 AM,31.0,Male,Other,False,HOMICIDE,HEROIN AND ETHANOL TOXICITY,NaN,NaN,NaN,NaN,True,5240 NORTH SHERIDAN APT 417,CHICAGO,-87.655620,41.977582,74058,"(41.977582, -87.6556196)"
12656,ME2016-04092,08/23/2016 01:37:00 AM,08/23/2016 06:45:00 AM,4.0,Female,Black,False,HOMICIDE,THERMAL INJURIES AND CARBON MONOXIDE TOXICITY,NaN,NaN,NaN,NaN,False,8112 S. Essex Avenue,CHICAGO,-87.564245,41.747711,68043,"(41.7477108, -87.5642452)"
12657,ME2016-04093,08/23/2016 01:37:00 AM,08/23/2016 06:45:00 AM,7.0,Female,Black,False,HOMICIDE,THERMAL INJURIES AND CARBON MONOXIDE TOXICITY,NaN,NaN,NaN,NaN,False,8112 S. Essex Avenue,CHICAGO,-87.564245,41.747711,68054,"(41.7477108, -87.5642452)"
12660,ME2016-04096,08/23/2016 01:37:00 AM,08/23/2016 06:45:00 AM,56.0,Male,Black,False,HOMICIDE,THERMAL INJURIES AND CARBON MONOXIDE TOXICITY,NaN,NaN,NaN,NaN,False,8114 S. Essex Avenue,CHICAGO,-87.564246,41.747673,67699,"(41.7476732, -87.5642456)"
13050,ME2016-04490,09/16/2016 02:45:00 AM,09/16/2016 03:34:00 AM,59.0,Male,White,True,HOMICIDE,CARBON MONOXIDE TOXICITY,GARAGE FIRE,NaN,NaN,NaN,False,2151 W 21st Street,CHICAGO,-87.680361,41.853700,65250,"(41.8536999, -87.6803607)"

### Okay, nope, we were wrong.

Those were almost **all from fires**. Apparently homicide is not the best place to go looking for toxicity. What's the most popular manner of death for primary causes involving toxicity?

- *Tip: Remember that `['colname']` is the same as `.colname`. You can't do `.col with spaces` so you'll need to do `['col with spaces']` a lot in this dataset
- *Tip: Or I guess if you really wanted to, you could rename your columns to have spaces in them (IF YOU DO THIS DON'T DO IT IN EXCEL BECAUSE IT WILL PROBABLY BREAK YOUR CSV.)*

In [21]:
df[df['Manner of Death'].str.contains('HOMICIDE').fillna(value=False) & df['Primary Cause'].str.contains('TOXICITY').fillna(value=False)]

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
3702,ME2015-00519,02/03/2015 08:21:00 AM,02/04/2015 08:34:00 AM,98.0,Female,Black,False,HOMICIDE,MORPHINE AND HYDROCODONE TOXICITY,NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,True,16300 louis Ave,SOUTH HOLLAND,-87.609278,41.598109,64404,"(41.5981086, -87.6092784)"
5395,ME2015-02286,05/27/2015 03:15:00 PM,06/03/2015 07:25:00 PM,28.0,Female,White,False,HOMICIDE,"COMPLICATIONS OF AMITRIPTYLINE AND METABOLITE,...",NaN,NaN,NaN,NaN,False,1102 S. Springinsguth Rd. #1D,SCHAUMBURG,-88.119741,42.005376,60663,"(42.005376, -88.1197414)"
6144,ME2015-03058,07/18/2015 07:00:00 AM,07/19/2015 02:05:00 AM,10.0,Male,Black,False,HOMICIDE,CARBON MONOXIDE TOXICITY,INCENDIARY HOUSE FIRE,NaN,NaN,NaN,False,8327 S. DREXEL,CHICAGO,-87.602328,41.743167,68218,"(41.7431675, -87.6023283)"
6764,ME2015-03692,08/29/2015 09:41:00 AM,08/29/2015 01:00:00 PM,28.0,Male,White,True,HOMICIDE,CARBON MONOXIDE TOXICITY,HOUSE FIRE,NaN,NaN,NaN,False,5209 S Lorel Avenue,CHICAGO,-87.755913,41.798035,72663,"(41.7980351, -87.7559129)"
6765,ME2015-03693,08/29/2015 09:41:00 AM,08/29/2015 01:00:00 PM,63.0,Male,Other,False,HOMICIDE,CARBON MONOXIDE TOXICITY,HOUSE FIRE,NaN,"ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE, ACUTE...",NaN,False,5205 S. Lorel,CHICAGO,-87.756075,41.798102,73036,"(41.7981017, -87.7560751)"
7612,ME2015-04564,10/22/2015 10:39:00 AM,10/22/2015 11:05:00 AM,31.0,Male,Other,False,HOMICIDE,HEROIN AND ETHANOL TOXICITY,NaN,NaN,NaN,NaN,True,5240 NORTH SHERIDAN APT 417,CHICAGO,-87.655620,41.977582,74058,"(41.977582, -87.6556196)"
12656,ME2016-04092,08/23/2016 01:37:00 AM,08/23/2016 06:45:00 AM,4.0,Female,Black,False,HOMICIDE,THERMAL INJURIES AND CARBON MONOXIDE TOXICITY,NaN,NaN,NaN,NaN,False,8112 S. Essex Avenue,CHICAGO,-87.564245,41.747711,68043,"(41.7477108, -87.5642452)"
12657,ME2016-04093,08/23/2016 01:37:00 AM,08/23/2016 06:45:00 AM,7.0,Female,Black,False,HOMICIDE,THERMAL INJURIES AND CARBON MONOXIDE TOXICITY,NaN,NaN,NaN,NaN,False,8112 S. Essex Avenue,CHICAGO,-87.564245,41.747711,68054,"(41.7477108, -87.5642452)"
12660,ME2016-04096,08/23/2016 01:37:00 AM,08/23/2016 06:45:00 AM,56.0,Male,Black,False,HOMICIDE,THERMAL INJURIES AND CARBON MONOXIDE TOXICITY,NaN,NaN,NaN,NaN,False,8114 S. Essex Avenue,CHICAGO,-87.564246,41.747673,67699,"(41.7476732, -87.5642456)"
13050,ME2016-04490,09/16/2016 02:45:00 AM,09/16/2016 03:34:00 AM,59.0,Male,White,True,HOMICIDE,CARBON MONOXIDE TOXICITY,GARAGE FIRE,NaN,NaN,NaN,False,2151 W 21st Street,CHICAGO,-87.680361,41.853700,65250,"(41.8536999, -87.6803607)"

### Okay, toxicity deaths (overdoses) are mostly accidents. Let's look at the first 30 accidental deaths involving toxicity.

- *Tip: Remember your parentheses!*

In [22]:
df[df['Primary Cause'].str.contains('TOXICITY').fillna(value=False)].head(30)

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
15,ME2018-01127,03/03/2018 02:15:00 AM,03/03/2018 02:24:00 AM,37.0,Male,White,False,ACCIDENT,"COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...",NaN,NaN,NaN,NaN,True,6547 W. 111TH APT W-27,WORTH,-87.781732,41.689640,63784,"(41.6896403, -87.7817317)"
45,ME2018-00910,02/19/2018 08:00:00 PM,02/19/2018 08:22:00 PM,56.0,Male,Black,False,ACCIDENT,COMBINED DRUG (COCAINE AND HEROIN) TOXICITY,NaN,NaN,NaN,NaN,True,7724 SOUTH LOOMIS BLVD #1,CHICAGO,-87.658932,41.753282,69589,"(41.7532818, -87.6589318)"
51,ME2018-00400,01/20/2018 11:15:00 AM,01/20/2018 11:57:00 AM,19.0,Male,White,False,ACCIDENT,HEROIN TOXICITY,NaN,NaN,NaN,NaN,True,"5719 S. Kimbark, Apt. 3",CHICAGO,-87.594142,41.790743,77880,"(41.7907435, -87.5941419)"
53,ME2018-00643,02/03/2018 10:45:00 AM,02/03/2018 11:11:00 AM,35.0,Male,White,False,ACCIDENT,"ETHANOL AND COMBINED DRUG (PROBABLE HEROIN, CY...",NaN,NaN,NaN,NaN,True,"2540 N. Manheim Road, Rm#215",FRANKLIN PARK,NaN,NaN,77879,NaN
54,ME2018-00671,02/05/2018 12:00:00 AM,02/05/2018 12:10:00 AM,27.0,Male,White,False,ACCIDENT,COMBINED FENTANYL AND PROBABLE HEROIN TOXICITY,NaN,NaN,OBESITY,NaN,True,3435 W. VAN BUREN,CHICAGO,-87.711994,41.875391,77910,"(41.8753913, -87.7119935)"
65,ME2018-01129,03/03/2018 03:45:00 AM,03/03/2018 04:31:00 AM,34.0,Male,Black,False,ACCIDENT,ACUTE ETHANOL TOXICITY,NaN,NaN,NaN,NaN,False,7899 SOUTH SHORE,CHICAGO,-87.548113,41.752056,68080,"(41.7520559, -87.5481134)"
69,ME2018-01356,03/15/2018 01:31:00 PM,03/15/2018 01:44:00 PM,26.0,Male,White,False,ACCIDENT,"FENTANYL, HEROIN, AND ALPRAZOLAM TOXICITY",NaN,NaN,NaN,NaN,True,710 N. 4TH AVENUE,MAYWOOD,-87.838564,41.893982,77870,"(41.8939818, -87.8385636)"
90,ME2017-05713,12/07/2017 09:00:00 AM,12/07/2017 09:33:00 AM,43.0,Male,White,False,SUICIDE,"COMBINED ALPRAZOLAM, HYDROCODONE, ACETAMINOPHE...",NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,True,"920 Ridge Square, Unit 209",ELK GROVE VILLAGE,-87.989562,42.003373,59870,"(42.0033733, -87.9895624)"
93,ME2018-01560,03/29/2018 06:50:00 PM,03/29/2018 07:12:00 PM,38.0,Male,Asian,False,ACCIDENT,COCAINE AND FENTANYL TOXICITY,NaN,NaN,NaN,NaN,True,535 N MICHIGAN AVE #2705,CHICAGO,-87.623541,41.891975,66297,"(41.8919752, -87.6235405)"
99,ME2018-01570,03/30/2018 03:33:00 PM,03/30/2018 04:20:00 PM,50.0,Male,White,False,ACCIDENT,"COCAINE, FENTANYL AND ACETYL FENTANYL TOXICITY",NaN,NaN,NaN,NaN,True,1042 N. KNOLLWOOD DR. UNIT A,SCHAUMBURG,-88.138219,42.044579,62417,"(42.0445787, -88.1382195)"
102,ME2018-01574,03/30/2018 10:43:00 PM,03/30/2018 11:03:00 PM,40.0,Female,White,False,ACCIDENT,"COMBINED DRUG (FENTANYL, METHADONE, AND ALPRAZ...",NaN,NaN,NaN,NaN,True,4345 AUTHUR AVE.,BROOKFIELD,NaN,NaN,63618,NaN
106,ME2018-01103,03/01/2018 02:02:00 PM,03/01/2018 02:45:00 PM,68.0,Male,Black,False,ACCIDENT,COMBINED DRUG (FENTANYL AND METHADONE) TOXICITY,NaN,NaN,NaN,NaN,True,1541 SOUTH HAMLIN,CHICAGO,-87.719819,41.859519,78255,"(41.8595195, -87.7198186)"
107,ME2018-02197,05/07/2018 09:27:00 AM,05/08/2018 05:23:00 AM,38.0,Female,White,False,ACCIDENT,FENTANYL AND COCAINE TOXICITY,NaN,NaN,NaN,NaN,True,15611 DIXIE HWY (APT 2),HARVEY,-87.669333,41.605710,78760,"(41.6057103, -87.6693327)"
108,ME2017-05182,11/04/2017 08:45:00 PM,11/04/2017 09:03:00 PM,50.0,Male,Black,False,ACCIDENT,HEROIN AND ETHANOL TOXICITY,NaN,NaN,NaN,NaN,True,5319 S. WALCOTT,CHICAGO,-87.671718,41.797034,77967,"(41.7970338, -87.6717184)"
109,ME2017-05643,12/02/2017 02:50:00 PM,12/02/2017 02:44:00 PM,45.0,Male,White,False,ACCIDENT,"COMBINED DRUG (HEROIN, FENTANYL, AND ACETYL FE...",NaN,NaN,NaN,NaN,True,4023 West Congress Parkway,CHICAGO,-87.726373,41.874299,77943,"(41.8742991, -87.7263732)"
128,ME2018-02201,04/10/2018 01:14:00 AM,04/14/2018 09:20:00 PM,57.0,Female,White,False,ACCIDENT,COMBINED DRUG (BENZODIAZEPINE AND PROBABLE HER...,NaN,NaN,NaN,NaN,True,411 FOREST PRESERVE DRIVE.,WOOD DALE,NaN,NaN,78485,NaN
161,ME2018-02220,05/02/2018 12:00:00 PM,05/05/2018 03:17:00 PM,35.0,Female,White,False,ACCIDENT,COMPLICATIONS OF METHADONE TOXICITY,NaN,NaN,NaN,NaN,True,15715 INDEPENDENCE CT,OAK FOREST,-87.757451,41.605997,78072,"(41.6059968, -87.7574509)"
175,ME2018-00926,02/20/2018 12:00:00 PM,02/20/2018 12:36:00 PM,39.0,Male,White,True,ACCIDENT,COMBINED HEROIN AND FENTANYL TOXICITY,NaN,NaN,NaN,NaN,True,4345 SOUTH PACKERS,NaN,-87.657687,41.814700,78047,"(41.8147004, -87.6576873)"
193,ME2017-04357,09/16/2017 03:46:00 AM,09/16/2017 04:01:00 AM,66.0,Male,White,False,ACCIDENT,FENTANYL AND ACETYL FENTANYL TOXICITY,NaN,NaN,NaN,NaN,True,7835 WEST CRESSETT,ELMWOOD PARK,-87.822402,41.930199,78115,"(41.9301994, -87.8224024)"
228,ME2016-03209,06/30/2016 09:45:00 AM,06/30/2016 10:02:00 AM,57.0,Male,White,False,ACCIDENT,ACUTE OXYCODONE AND OXYMORPHONE TOXICITY,NaN,NaN,NaN,NaN,True,7101 Emerson Street,MORTON GROVE,-87.803695,42.051732,60635,"(42.0517323, -87.8036954)"
232,ME2018-01362,03/16/2018 01:53:00 AM,03/16/2018 02:06:00 AM,49.0,Male,White,False,ACCIDENT,"COMBINED ETHANOL, NORDIAZEPAM, AND FENTANYL TO...",NaN,NaN,NaN,NaN,True,945 W. BELMONT AVE.,CHICAGO,-87.653295,41.939872,78209,"(41.9398725, -87.6532951)"
233,ME2018-01822,04/15/2018 09:00:00 AM,04/15/2018 09:21:00 AM,57.0,Male,White,False,ACCIDENT,"ALCOHOL, TEMAZEPAM AND ALPRAZOLAM TOXICITY",NaN,NaN,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,False,252 W. JENNIFER LANE #1,PALATINE,-88.049872,42.124696,78220,"(42.1246964, -88.0498716)"
243,ME2018-02302,05/10/2018 05:00:00 PM,05/14/2018 02:50:00 PM,61.0,Female,White,False,ACCIDENT,COMPLICATIONS OF OPIATE AND BENZODIAZEPINE TOX...,NaN,NaN,"DIABETES MELLITUS, HYPERTENSIVE CARDIOVASCULAR...",NaN,True,3036 W. BELMONT,CHICAGO,-87.704238,41.939582,78349,"(41.9395819, -87.7042375)"
252,ME2017-00383,01/22/2017 09:30:00 AM,01/22/2017 10:00:00 AM,53.0,Female,White,False,ACCIDENT,"ETHANOL AND COMBINED DRUG (HYDROCODONE, LEVETI...",NaN,NaN,NaN,NaN,True,2519 NORTH ROCKWELL STREET,CHICAGO,-87.692363,41.927295,74629,"(41.9272948, -87.6923633)"
255,ME2017-06107,12/27/2017 06:18:00 AM,12/30/2017 07:28:00 AM,27.0,Male,White,False,ACCIDENT,"FENTANYL, DIAZEPAM, LORAZEPAM, AND SERTRALINE ...",NaN,NaN,HYPOTHERMIA DUE TO COLD EXPOSURE,NaN,True,135 E OAK ST,CHICAGO,-87.624631,41.900754,78228,"(41.9007545, -87.6246305)"
353,ME2018-02380,05/20/2018 09:25:00 AM,05/20/2018 10:03:00 AM,40.0,Male,Black,False,ACCIDENT,ETHANOL TOXICITY,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, CHRONIC E...",NaN,False,6803 S. Clyde,CHICAGO,-87.573933,41.771578,78574,"(41.7715777, -87.5739333)"
356,ME2018-00475,01/23/2018 09:42:00 PM,01/23/2018 09:59:00 PM,53.0,Female,Black,False,ACCIDENT,COCAINE TOXICITY,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,False,14134 PAGE ST.,DIXMOOR,-87.659803,41.632238,58259,"(41.6322383, -87.6598032)"
388,ME2018-01138,03/03/2018 09:30:00 AM,03/03/2018 10:13:00 AM,27.0,Male,Black,False,ACCIDENT,FENTANYL AND ALPRAZOLAM TOXICITY,NaN,NaN,NaN,NaN,True,7829 S. PEORIA 2ND FLOOR APT,CHICAGO,-87.646202,41.751532,68896,"(41.7515321, -87.6462021)"
396,ME2018-01232,03/08/2018 02:10:00 PM,03/08/2018 02:42:00 PM,36.0,Male,White,True,ACCIDENT,"COMBINED DRUG (CARFENTANIL, FURANYL FENTANYL, ...",NaN,NaN,NaN,NaN,True,1600 N. WESTERN AND NORTH AVE.,CHICAGO,-87.687300,41.910342,69942,"(41.9103425, -87.6873004)"
398,ME2018-01248,03/09/2018 12:00:00 AM,03/09/2018 11:41:00 AM,45.0,Female,Black,False,ACCIDENT,COCAINE TOXICITY,NaN,NaN,NaN,NaN,False,3554 W Ohio,CHICAGO,-87.715687,41.891864,69058,"(41.8918636, -87.7156869)"

## Wow, that's a lot of drug overdoses. What's more popular for overdosing: heroin, fentanyl, cocaine, or ethanol?

You can count something like "COMBINED ETHANOL, NORDIAZEPAM, AND FENTANYL TOXICITY" under both ethanol and fentanyl.

- *Tip: Search for them individually*

In [23]:
df['Primary Cause'].str.contains('HEROIN').fillna(value=False).value_counts(dropna=False)

False    20612
True      2022
Name: Primary Cause, dtype: int64

In [24]:
df['Primary Cause'].str.contains('FENTANYL').value_counts(dropna=False)

False    21017
True      1493
NaN        124
Name: Primary Cause, dtype: int64

In [25]:
df['Primary Cause'].str.contains('COCAINE').value_counts(dropna=False)

False    21446
True      1064
NaN        124
Name: Primary Cause, dtype: int64

In [26]:
df['Primary Cause'].str.contains('ETHANOL').value_counts(dropna=False)

False    21183
True      1327
NaN        124
Name: Primary Cause, dtype: int64

In [27]:
print('heroin is the most popular overdose')

heroin is the most popular overdose

# Cleaning up Primary Cause

Let's stop investigating for a second and maybe clean up this "Primary Cause" column.

## What are the most common Primary Cause of death? Include `NaN` values

- *Tip: There is an option that keeps `NaN` values when counting things in a column.*

In [28]:
df['Primary Cause'].value_counts(dropna=False)

ORGANIC CARDIOVASCULAR DISEASE                                                                             1983
MULTIPLE GUNSHOT WOUNDS                                                                                    1377
HYPERTENSIVE CARDIOVASCULAR DISEASE                                                                        1177
ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                                                                     974
HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                                                        960
MULTIPLE INJURIES                                                                                           941
HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                                                    460
PENDING                                                                                                     452
GUNSHOT WOUND OF HEAD                                                                                       440
HANGING                                                                                                     323
MULTIPLE BLUNT FORCE INJURIES                                                                               299
HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULAR DISEASE                                                     298
HEROIN TOXICITY                                                                                             286
ASPHYXIA                                                                                                    255
UNDETERMINED                                                                                                242
CLOSED HEAD INJURIES                                                                                        217
CHRONIC ETHANOLISM                                                                                          205
CORONARY ATHEROSCLEROSIS                                                                                    203
DROWNING                                                                                                    185
COMPLICATIONS OF FALL                                                                                       181
COMPLICATIONS OF CHRONIC ETHANOLISM                                                                         177
COMPLICATIONS OF MULTIPLE INJURIES                                                                          160
ASPHYXIATION                                                                                                151
ATHEROSCLEROTIC CARDIOVASCULAR DISEASE                                                                      140
GUNSHOT WOUND OF THE HEAD                                                                                   132
NaN                                                                                                         124
PULMONARY THROMBOEMBOLISM                                                                                   122
GUNSHOT WOUND OF CHEST                                                                                      120
DIABETIC KETOACIDOSIS                                                                                       107
FENTANYL TOXICITY                                                                                           103
                                                                                                           ...
VALVULAR INFECTIVE ENDOCARDITIS                                                                               1
COMBINED DRUG (FENTANYL, ACETYL FENTANYL AND PROBABLE HEROIN) TOXICITY.                                       1
COMBINED DRUG (DOXEPIN, DULOXETINE, METOPROLOL, GABAPENTIN, ALPRAZOLAM) TOXICITY                              1
COMBINED DRUG (DESPROPIONYL FENTANYL (4-ANPP), ACRYL FENTANYL, AND DIPHENHYDRAMINE) TOXICITY                  1
COMBINED DRUG (HEROIN, FENTANYL AND ALPRAZOLAM) TOXICITY                                                      1
GUNSHOT WOUND OF CHIN                                                                                         1
COMBINED DRUG (CODEINE, MORPHINE) TOXICITY                                                                    1
MULTIPLE DRUG (FURANYL-FENTANYL,DESPROPIONYL-FENTANYL/4-ANPP, 7-AMINO-CLONAZEPAM) TOXICITY                    1
COMPLICATIONS OF CEREBRAL ARTERY ANEURYSM RUPTURE                                                             1
COMBINED DRUG (METHOXYACETYL FENTANYL, CYCLOPROPYL FENTANYL, HEROIN, ALPRAZOLAM, . . .                        1
BACTERIAL ENDOCARDITIS                                                                                        1
HYDROCODONE, ALPRAZOLAM, AND HYDROMORPHONE INTOXICATION                                                       1
COMPRESSIONAL ASPHYXIA                                                                                        1
COMPLICATIONS OF BLUNT ABDOMINAL TRAUMA                                                                       1
MIXED DRUG TOXICITY (COCAINE, FENTANYL)                                                                       1
ALCOHOL, AMPHETAMINE, COCAINE, AND HEROIN TOXICITY                                                            1
COMBINED DRUG (METHADONE, DIAZEPAM AND ALPRAZOLAM) TOXICITY                                                   1
ALCOHOL, ACETAMINOPHEN, AND DIPHENHYDRAMINE INTOXICATION                                                      1
COMBINED THIORIDAZINE, DIAZEPAM, LORAZEPAM, FLURAZEPAM, MIRTAZAPINE, AND ESZOPICLONE/ZOPICLONE TOXICITY       1
1,1 - DIFLUOROETHANE TOXICITY                                                                                 1
HYPERTENSIVE  ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE                                                         1
COMPLICATIONS OF CHRONIC ETHANANOLISM                                                                         1
COCAINE, TRAMADOL AND ETHANOL TOXICITY                                                                        1
CYCLOPROPYL FENTANYL AND TOPIRAMATE TOXICITY                                                                  1
COMBINED DRUG (MORPHINE, NORDIAZEPAM, GABAPENTIN, CITALOPRAM) TOXICITY                                        1
COMBINED DRUG TOXICITY (ACRYL FENTANYL AND PROBABLE HEROIN)                                                   1
MULTIPLE INCISED AND STAB WOUNDS                                                                              1
COMPLICATIONS OF INJURIES TO LEG                                                                              1
COMBINED DRUG (ALPRAZOLAM, METHADONE AND AMPHETAMINE) TOXICITY                                                1
COMBINED HEROIN, DESPROPRIONYL FENTANYL (4-ANPP), ACRYL FENTANYL AND BUTALBITAL TOXICITY                      1
Name: Primary Cause, Length: 3994, dtype: int64

## That was horrible looking. I don't want to read through that - how many `NaN` causes of death are there?

- *Tip: You can use `isnull()` to see if it's missing data, but how do you count the results?*

In [29]:
df['Primary Cause'].isnull().value_counts()

False    22510
True       124
Name: Primary Cause, dtype: int64

## Remove all rows where the primary cause of death has not been filled out.

- *Tip: confirm that you have 22510 rows when you're done*

In [30]:
df = df.dropna(subset=['Primary Cause'])

In [31]:
df['Primary Cause'].dropna()

5                                        MULTIPLE INJURIES
6                                    GUNSHOT WOUND TO HEAD
7                                                  PENDING
8                                                  PENDING
9                                                  PENDING
10                                   GUNSHOT WOUND OF HEAD
11                                       MULTIPLE INJURIES
12                                       MULTIPLE INJURIES
13                         COMPLICATIONS OF MORBID OBESITY
14                                 MULTIPLE GUNSHOT WOUNDS
15       COMBINED DRUG (COCAINE, HEROIN, FENTANYL) TOXI...
16                           MULTIPLE SHARP FORCE INJURIES
17                                    CLOSED HEAD INJURIES
18                          ORGANIC CARDIOVASCULAR DISEASE
19                                 MULTIPLE GUNSHOT WOUNDS
20                        MULTIPLE STAB AND INCISED WOUNDS
21                                                 PENDING
22                                     STAB WOUND OF CHEST
23                                       MULTIPLE INJURIES
24                                       CEREBRAL INJURIES
25                                                 PENDING
27       ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULA...
28       HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...
32                                                 PENDING
33                                                 PENDING
34                          ORGANIC CARDIOVASCULAR DISEASE
35                                 MULTIPLE GUNSHOT WOUNDS
36                               GUNSHOT WOUND OF THE HEAD
37                                 MULTIPLE GUNSHOT WOUNDS
38                                   GUNSHOT WOUND OF HEAD
                               ...
22602                                              PENDING
22603                                COMPLICATIONS OF FALL
22604    HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...
22605                                    NON-HUMAN REMAINS
22606    HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...
22607                                              PENDING
22608                       ORGANIC CARDIOVASCULAR DISEASE
22609                                              PENDING
22610                        MULTIPLE BLUNT FORCE INJURIES
22611                       ORGANIC CARDIOVASCULAR DISEASE
22612                       ORGANIC CARDIOVASCULAR DISEASE
22613                                              PENDING
22614                                              PENDING
22615                                              PENDING
22616                                              PENDING
22617                                              PENDING
22618                       ORGANIC CARDIOVASCULAR DISEASE
22619                       ORGANIC CARDIOVASCULAR DISEASE
22621                                              PENDING
22623                                              PENDING
22624                       ORGANIC CARDIOVASCULAR DISEASE
22625                       ORGANIC CARDIOVASCULAR DISEASE
22626                                              PENDING
22627                                              PENDING
22628                       GUNSHOT WOUND OF RIGHT BUTTOCK
22629                                              PENDING
22630                       ORGANIC CARDIOVASCULAR DISEASE
22631                                              PENDING
22632                                GUNSHOT WOUND OF HEAD
22633                       ORGANIC CARDIOVASCULAR DISEASE
Name: Primary Cause, Length: 22510, dtype: object

In [32]:
df.shape

(22510, 20)

# Cardiovascular disease

Cardiovascular disease (heart disease) is the number one or number two killer in America.

### Filter for only rows where cardiovascular disease was a primary cause

- *Tip: I hope you know how to deal with the `NaN` error message by now!*

In [33]:
cardi_v = df[df['Primary Cause'].str.contains('CARDIOVASCULAR')]

In [34]:
dc = cardi_v

In [35]:
dc

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
18,ME2018-01135,03/03/2018 09:30:00 AM,03/03/2018 10:05:00 AM,55.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,10034 S. MICHICAGN AVE. APT 2,NaN,NaN,NaN,71064,NaN
27,ME2018-02131,05/03/2018 07:15:00 PM,05/03/2018 08:00:00 PM,48.0,Male,White,False,NATURAL,ATHEROSCLEROTIC AND HYPERTENSIVE CARDIOVASCULA...,NaN,NaN,OBESITY,NaN,False,2631 West Rascher Avenue,CHICAGO,-87.695479,41.980215,77843,"(41.9802154, -87.6954789)"
28,ME2018-02134,05/03/2018 06:20:00 PM,05/03/2018 07:01:00 PM,76.0,Male,White,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,DIABETES MELLITUS AND OBESITY,NaN,False,8108 ODELL AVENUE,BRIDGEVIEW,-87.803607,41.744014,77849,"(41.7440145, -87.8036075)"
34,ME2018-02170,05/06/2018 02:05:00 PM,05/06/2018 02:46:00 PM,64.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,4250 S. PRINCETON APT 412,CHICAGO,-87.634704,41.816742,78016,"(41.8167422, -87.6347043)"
43,ME2014-01078,10/18/2014 02:30:00 PM,10/18/2014 03:55:00 PM,67.0,Male,White,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,610 SOUTH MAWATA,MOUNT PROSPECT,NaN,NaN,61280,NaN
57,ME2018-02186,05/07/2018 12:26:00 PM,05/07/2018 12:53:00 PM,66.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,146 N. CENTRAL #1D,CHICAGO,-87.765474,41.883634,78010,"(41.8836343, -87.7654736)"
64,ME2018-00995,02/23/2018 09:35:00 AM,02/23/2018 09:50:00 AM,70.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,5700 NORTH SHERIDAN APT 1003,NaN,-87.655755,41.985857,55722,"(41.9858569, -87.6557545)"
66,ME2018-01148,03/03/2018 04:30:00 PM,03/03/2018 05:09:00 PM,58.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,OBESITY,NaN,False,11011 JORDAN DRIVE,OAK LAWN,NaN,NaN,59051,NaN
71,ME2018-01411,03/19/2018 12:00:00 AM,03/19/2018 11:04:00 AM,59.0,Female,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,"CHRONIC OBSTRUCTIVE PULMONARY DISEASE, DIABETE...",NaN,False,7804 South Maryland 1st floor,CHICAGO,-87.604086,41.753007,77882,"(41.7530066, -87.6040862)"
72,ME2018-01910,05/01/2018 10:50:00 AM,05/01/2018 10:59:00 AM,65.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NON-TRAUMATIC SEIZURE DISORDER,NaN,False,841 Williams Street #1D,CALUMET CITY,-87.545633,41.599656,77889,"(41.599656, -87.5456329)"
77,ME2018-02047,05/04/2018 01:03:00 PM,05/04/2018 01:13:00 PM,77.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,1127 DARTMOUTH RD,FLOSSMOOR,-87.665969,41.541767,78304,"(41.5417673, -87.6659691)"
80,ME2014-00002,08/11/2014 09:35:00 AM,08/11/2014 01:00:00 PM,57.0,Male,White,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,345 W. Fullerton Pkwy #503,CHICAGO,-87.638275,41.925278,67261,"(41.9252778, -87.6382754)"
81,ME2014-00003,08/11/2014 09:05:00 AM,08/11/2014 09:40:00 AM,74.0,Male,Black,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,520 E. 47th Street Room 325,CHICAGO,-87.613031,41.809499,76196,"(41.8094993, -87.613031)"
84,ME2014-00006,08/10/2014 07:15:00 AM,08/10/2014 08:00:00 AM,82.0,Female,White,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,4037 North Major,CHICAGO,-87.769174,41.954301,73326,"(41.9543011, -87.769174)"
97,ME2018-01567,03/30/2018 10:49:00 AM,03/30/2018 10:54:00 AM,73.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,"3532 WENONAH AVENUE, BASEMENT",BERWYN,-87.799095,41.827444,57283,"(41.8274439, -87.7990951)"
105,ME2018-02195,05/07/2018 11:30:00 PM,05/08/2018 11:57:00 PM,44.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,222 S. HAMLIN (2ND FLOOR APT B18 ),CHICAGO,-87.721253,41.877339,78100,"(41.8773392, -87.7212533)"
122,ME2018-02117,05/03/2018 09:00:00 AM,05/03/2018 09:15:00 AM,78.0,Female,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,408 S Scovel; unit 1N,OAK PARK,-87.785150,41.887006,78104,"(41.8870064, -87.7851498)"
123,ME2018-02202,05/08/2018 01:26:00 PM,05/08/2018 03:00:00 PM,47.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,DIABETES MELLITUS,NaN,False,21329 Illinois Street,MATTESON,-87.701184,41.501797,78143,"(41.501797, -87.7011843)"
124,ME2018-02207,05/08/2018 01:31:00 PM,05/08/2018 01:49:00 PM,71.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,212 SOUTH OAK PARK AVENUE APT #201,OAK PARK,-87.793900,41.884475,78276,"(41.8844746, -87.7938998)"
135,ME2018-02215,05/08/2018 08:28:00 PM,05/08/2018 09:20:00 PM,47.0,Male,White,True,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,DIABETES MELLITUS; MORBID OBESITY,NaN,False,4551 West Altgeld Street,CHICAGO,-87.741105,41.926040,78116,"(41.9260404, -87.7411047)"
139,ME2018-02252,05/11/2018 10:55:00 AM,05/11/2018 11:05:00 AM,61.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,1856 W CERMAK RD,CHICAGO,-87.673137,41.852413,78107,"(41.8524131, -87.6731375)"
151,ME2018-02159,05/05/2018 07:45:00 PM,05/05/2018 08:10:00 PM,77.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,3409 S. 55TH AVENUE,CICERO,-87.760820,41.830551,77990,"(41.8305508, -87.7608196)"
170,ME2018-02225,05/09/2018 01:30:00 PM,05/09/2018 01:44:00 PM,70.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,"3656 W. HURON STREET, UNIT #507",CHICAGO,-87.718250,41.893809,78905,"(41.8938088, -87.7182497)"
171,ME2018-02210,05/08/2018 12:00:00 PM,05/08/2018 12:36:00 PM,73.0,Female,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,"OBESITY, DIABETES MELIITUS, CHRONIC OBSTRUCTIV...",NaN,False,"4930 S. LANGLEY AVENUE, UNIT #1011",CHICAGO,-87.609218,41.805032,78090,"(41.8050321, -87.6092179)"
178,ME2018-02230,05/09/2018 03:43:00 PM,05/09/2018 04:35:00 PM,60.0,Female,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,24 158TH BUILDING 11 APT 4E,CALUMET CITY,-87.570861,41.604922,78040,"(41.6049219, -87.5708611)"
191,ME2018-02234,05/09/2018 08:42:00 PM,05/09/2018 10:34:00 PM,58.0,Female,White,True,NATURAL,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,NaN,NaN,DIABETES MELLITUS; METASTATIC BREAST CANCER,NaN,False,6035 W. FULLERTON AVE,CHICAGO,-87.777107,41.923579,78329,"(41.9235787, -87.7771075)"
197,ME2018-02263,05/01/2018 10:00:00 AM,05/01/2018 10:13:00 AM,95.0,Female,White,False,NaN,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,"5219 N. POTAWATOMIE, UNIT 101",CHICAGO,-87.842353,41.974329,78171,"(41.9743293, -87.8423531)"
201,ME2018-02213,05/08/2018 09:15:00 PM,05/08/2018 09:35:00 PM,63.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,8528 SOUTH 83RD AVENUE,HICKORY HILLS,-87.826281,41.736017,78140,"(41.7360172, -87.8262807)"
209,ME2018-02286,05/13/2018 11:00:00 AM,05/13/2018 11:38:00 AM,81.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,7821 W. 89TH STR. #1W,HICKORY HILLS,-87.814269,41.729500,78227,"(41.7294997, -87.8142692)"
213,ME2018-02285,05/13/2018 11:30:00 AM,05/13/2018 12:22:00 PM,48.0,Male,White,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,OBESITY,NaN,False,17037 GRISSOM DRIVE #2N,TINLEY PARK,-87.815308,41.581108,78312,"(41.5811079, -87.8153083)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22543,ME2018-02011,04/16/2018 12:00:00 AM,04/16/2018 03:37:00 PM,55.0,Male,Black,False,NATURAL,HYPERTENSIVE CARDIOVASCULAR DISEASE,NaN,NaN,DIABETES MELLITUS,NaN,False,"7907 S, Eberhart",CHICAGO,-87.612291,41.750915,74948,"(41.7509154, -87.6122906)"
22546,ME2018-02014,04/27/2018 03:20:00 PM,04/27/2018 03:42:00 PM,54.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,68 E. WACKER PL,CHICAGO,-87.625381,41.887069,63628,"(41.8870687, -87.6253815)"
22552,ME2018-02019,04/27/2018 07:09:00 PM,04/27/2018 07:18:00 PM,69.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,MORBID OBESITY; DIABETES MELLITUS,NaN,False,449 SANDRA LANE,ELGIN,-88.255706,42.028030,60615,"(42.0280296, -88.2557056)"
22555,ME2018-02037,04/27/2018 12:00:00 AM,04/29/2018 12:24:00 PM,94.0,Male,White,False,NATURAL,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,NaN,NaN,"END STAGE RENAL DISEASE, CHRONIC OBSTRUCTIVE P...",NaN,False,2732 N. HAMPDEN,CHICAGO,-87.642483,41.931412,76983,"(41.931412, -87.6424828)"
22556,ME2018-02038,04/29/2018 12:00:00 PM,04/29/2018 12:23:00 PM,80.0,Male,Black,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,NaN,NaN,False,3333 WEST MAPLE APT 714,CHICAGO,-87.710052,41.883377,77794,"(41.883377, -87.7100524)"
22558,ME2018-02040,04/29/2018 01:05:00 PM,04/29/2018 01:37:00 PM,72.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,NaN,False,1832 187TH STREET,HOMEWOOD,-87.661477,41.549992,77782,"(41.5499918, -87.6614767)"
22559,ME2018-02041,04/29/2018 03:00:00 PM,04/29/2018 03:51:00 PM,82.0,Female,White,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,408 RIDGE CIRCLE,STREAMWOOD,-88.160042,42.024387,58262,"(42.0243866, -88.160042)"
22564,ME2018-02046,04/29/2018 06:41:00 PM,04/29/2018 06:50:00 PM,80.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,7132 WEST 26TH STREET #02,BERWYN,-87.802409,41.842822,57031,"(41.8428225, -87.8024091)"
22568,ME2018-02057,04/29/2018 07:15:00 PM,04/29/2018 07:25:00 PM,62.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,312 N WILLIAM,MOUNT PROSPECT,-87.928877,42.073167,60962,"(42.0731669, -87.9288773)"
22569,ME2018-02058,04/22/2018 12:07:00 PM,04/22/2018 12:44:00 PM,65.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,1242 LEEWOOD CT,ELGIN,-88.243335,42.044759,77642,"(42.0447586, -88.2433353)"
22575,ME2018-02065,04/30/2018 03:45:00 PM,04/30/2018 04:00:00 PM,69.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,END STAGE RENAL DISEASE,NaN,False,4949 S. COTTAGE GROVE APT 812,CHICAGO,-87.606029,41.804449,77798,"(41.8044491, -87.606029)"
22576,ME2018-02066,04/30/2018 11:00:00 AM,04/30/2018 11:14:00 AM,75.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,5333 N. SHERIDAN RD. #21B,CHICAGO,-87.654376,41.979434,74510,"(41.9794337, -87.6543755)"
22579,ME2018-01213,01/07/2018 07:01:00 PM,01/07/2018 07:41:00 PM,66.0,Male,Black,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,DIABETES,NaN,False,6943 SOUTH INDIANA AVENUE,CHICAGO,-87.619872,41.767986,72842,"(41.7679856, -87.6198721)"
22588,ME2018-02135,05/03/2018 08:50:00 PM,05/03/2018 09:22:00 PM,64.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,890 OAK WOOD COURT,DES PLAINES,-87.901905,42.037572,77892,"(42.0375718, -87.9019049)"
22593,ME2018-02140,05/04/2018 09:50:00 AM,05/04/2018 10:44:00 AM,56.0,Male,White,True,NATURAL,HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,NaN,NaN,False,1301 S 47th Ave,CICERO,-87.741322,41.863613,78734,"(41.8636133, -87.7413222)"
22598,ME2018-02082,05/01/2018 10:30:00 AM,05/01/2018 11:15:00 AM,84.0,Female,Black,False,NaN,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,8906 S. MERRILL,CHICAGO,-87.572283,41.733168,68510,"(41.7331679, -87.5722831)"
22599,ME2018-02083,04/04/2018 07:45:00 PM,04/04/2018 08:05:00 PM,63.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,5207 W Fernaird # 3E,CHICAGO,NaN,NaN,75387,NaN
22600,ME2018-02084,05/01/2018 02:06:00 PM,05/01/2018 02:30:00 PM,71.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,"CHRONIC OBSTRUCTIVE PULMONARY DISEASE, DIABETE...",NaN,False,5839 S HARLEM AVE #417,CHICAGO,-87.801174,41.785279,77786,"(41.7852787, -87.8011736)"
22601,ME2018-02085,05/01/2018 04:06:00 PM,05/01/2018 04:20:00 PM,94.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,2470 N. CLARK #508,CHICAGO,-87.642117,41.927326,67333,"(41.9273255, -87.6421167)"
22604,ME2018-02088,05/01/2018 05:15:00 PM,05/01/2018 06:50:00 PM,50.0,Male,White,True,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,"DIABETES MELLITUS, CIRRHOSIS OF THE LIVER",NaN,False,"2832 WEST CERMAK, UNIT 2F",CHICAGO,-87.696780,41.852127,70244,"(41.8521269, -87.6967797)"
22606,ME2018-02090,05/01/2018 07:20:00 PM,05/01/2018 06:29:00 PM,48.0,Female,Black,False,NATURAL,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,NaN,NaN,CHRONIC KIDNEY DISEASE,NaN,False,201 W. 69TH STREET,CHICAGO,-87.630248,41.768766,72642,"(41.768766, -87.6302482)"
22608,ME2018-02074,05/01/2018 08:33:00 AM,05/01/2018 09:03:00 AM,62.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,2901 S. Michigan Avenue #504 South Commons,CHICAGO,-87.622834,41.841718,77971,"(41.8417184, -87.6228345)"
22611,ME2018-02091,05/01/2018 08:00:00 PM,05/01/2018 08:45:00 PM,55.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CIRRHOSIS OF UNKNOWN ETIOLOGY,NaN,False,1755 HENLEY ST #2N,GLENVIEW,-87.802212,42.070070,78280,"(42.0700695, -87.8022124)"
22612,ME2018-02081,05/01/2018 12:40:00 PM,05/01/2018 12:53:00 PM,61.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,"527 W. 14TH PLACE, PACIFIC GARDEN MISSION",CHICAGO,-87.640188,41.862401,78381,"(41.8624014, -87.640188)"
22618,ME2018-02110,05/02/2018 07:50:00 PM,05/02/2018 08:14:00 PM,72.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,"1341 W. 92ND STREET, UNIT #2",CHICAGO,-87.657078,41.726716,77789,"(41.7267165, -87.6570785)"
22619,ME2018-02111,05/02/2018 09:17:00 PM,05/02/2018 09:23:00 PM,91.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,2058 W. Hutchinson,CHICAGO,-87.681238,41.958973,67932,"(41.9589732, -87.6812383)"
22624,ME2018-02100,05/02/2018 08:08:00 AM,05/02/2018 08:21:00 AM,85.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,1127 Miller Lane;,BUFFALO GROVE,-87.978407,42.134728,77891,"(42.1347284, -87.9784066)"
22625,ME2018-02102,05/02/2018 12:10:00 PM,05/02/2018 12:19:00 PM,73.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,NaN,False,"549 W. ALDINE AVENUE, UNIT #203",CHICAGO,-87.643876,41.941953,77939,"(41.9419529, -87.6438762)"
22630,ME2018-02122,05/03/2018 12:29:00 PM,05/03/2018 12:39:00 PM,94.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,"CORONARY ARTERY DISEASE, HYPERTENSION, DIABETE...",NaN,False,16416 EVANS AVENUE,SOUTH HOLLAND,-87.600994,41.596634,78272,"(41.5966344, -87.6009945)"
22633,ME2018-02107,05/02/2018 04:53:00 PM,05/02/2018 05:11:00 PM,57.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,CHRONIC OBSTRUCTIVE PULMONARY DISEASE,NaN,False,3914 212 PL,MATTESON,-87.711457,41.504114,78828,"(41.5041136, -87.7114567)"

### What are the different types?

In [36]:
dc['Primary Cause'].str.extract("(.*) CARDIOVASCULAR")[0].value_counts()

ORGANIC                                                       2007
HYPERTENSIVE                                                  1182
ARTERIOSCLEROTIC                                               998
HYPERTENSIVE ARTERIOSCLEROTIC                                  991
HYPERTENSIVE AND ARTERIOSCLEROTIC                              478
HYPERTENSIVE AND ATHEROSCLEROTIC                               298
ATHEROSCLEROTIC                                                143
HYPERTENSIVE-ARTERIOSCLEROTIC                                   90
ORGANIC                                                         77
HYPERTENSIVE ATHEROSCLEROTIC                                    39
ATHEROSCLEROTIC AND HYPERTENSIVE                                16
ARTERIOSLCEROTIC                                                 9
HYPERTENSIVE AND OBESITY-RELATED                                 4
VALVULAR                                                         4
HYPERTENSIVE ARTERIOSCLEROSIS                                    3
ORGANIC ARTERIOSCLEROTIC                                         3
HYPERTENSIVE, ATHEROSCLEROTIC AND VALVULAR                       3
HYPERTENSIVE, ARTERIOSCLEROTIC AND VALVULAR                      3
HYPERTENSIVE AND VALVULAR                                        3
ARTERIORSCLEROTIC                                                3
OBESITY-RELATED                                                  3
HYPERTENSIC ARTERIOSCLEROTIC                                     3
HYPERTENSIVE ARTEROISCLEROTIC                                    2
ORGAINIC                                                         2
ARTERIOSCLEROTIC AND VALVULAR                                    2
ARTERIOSCLEROTIC                                                 2
HYPERTENSIVE ARTERIOCLEROTIC                                     2
HYPERTENSIC ATHEROSCLEROTIC                                      2
ATERIOSCLEROTIC                                                  2
COMPLICATIONS OF HYPERTENSIVE                                    2
                                                              ...
HYPERTENSIVE, ARTERIOSCLEROTIC                                   1
ARTERIOSCLEROITIC                                                1
HYEPRTENSIVE                                                     1
HYPERTENSIVE AND ARTERIORSCLEROTIC                               1
HYPERTENSION                                                     1
ATHEROSCLEROTIC AND OBESITY-RELATED                              1
COMPLICATIONS FROM FEMORAL ANGIOPLASTY FOR ATHEROSCLEROTIC       1
ARTERIOSCLEROTIC                                                 1
ARTERIOSCLEROTIC AND HYPERTENSIVE                                1
HYPERTENSIVE  ARTERIOSCLEROTIC                                   1
HYPERTENSIVE AND ATHROSCLEROTIC                                  1
COMPLICATIONS OF HYPERTENSIVE AND ATHEROSCLEROTIC                1
HYPERTENSIVE AND STRUCTURAL                                      1
HYPERTENSIVE ARTERIOSCLERITIC                                    1
HYPERTENSIVE ARTEIOSCLEROTIC                                     1
ATHEROSCEROTIC                                                   1
HYPERTENSIVE, VALVULAR, AND ARTERIOSCLEROTIC                     1
HYPERTENSIVE ARTERIOSCLERTIC                                     1
.HYPERTENSIVE                                                    1
HYPERTENSIVE ARTERTIOSCLEROTIC                                   1
ATHEROSCLEROTIC AND VALVULAR                                     1
ARTHEROSCLEROTIC                                                 1
AFTERIOSCLEROTIC                                                 1
HYPERTENSIVS                                                     1
HYPERTENSIVE ARTEROSCLEROTIC                                     1
ARTERIOACLEROTIC                                                 1
ATHEROSCLERTOTIC                                                 1
ARTERISCLEROTIC                                                  1
HYPERTENSIVE ARTERISCLEROTIC                                     1
PROBABLE DYSRHYTHMOGENIC                                         1
Name: 0, Length: 94, dtype: int64

### Replace all of those with a nice simple 'CARDIOVASCULAR DISEASE'

- *Tip: you can use `.replace` or `.str.replace`, but they each involve different things! I suggest `.replace`, it looks a little cleaner in this situation*
- *Tip: for `.replace`, you need to give it more options than usual*
c- *Tip: for `.str.replace`, it won't automatically save back into the column, you need to do that yourself*

In [37]:
dc['Primary Cause'].replace(*,'CARDIOVASCULAR', regex = True,inplace=True)

SyntaxError: invalid syntax (<ipython-input-37-8fcf0d54b5bd>, line 1)

### Check the top 5 primary causes. Cardiovascular disease should be first with about 28.4%

We could also clean up gunshots, but... let's just move on.

# The Opioid Epidemic

America has a [big problem with fentanyl](https://www.theatlantic.com/health/archive/2018/05/americas-opioid-crisis-is-now-a-fentanyl-crisis/559445/) and other opioids.

## Find all of the rows where fentanyl was part of the primary cause of death

We don't need `na=False` any more because we *dropped the rows without primary causes*.

In [ ]:
df

## Fentanyl and race

In the late 80's and 90's, the [crack cocaine epidemic](https://en.wikipedia.org/wiki/Crack_epidemic) swept through inner cities in the US. It was treated primarily as a crime problem, while many people say fentanyl and heroin overdoses are being treated as a medical problem due to the racial differences - the crack epidemic mainly affected Black communities, while fentanyl seems to be a problem for everyone.

### How does the racial breakdown of fentanyl deaths compare to the racial breakdown of other causes of death? How about compared to causes of accidental death?

### Now compare it to homicides

### Now compare it to suicide

## These differences seems kind of crazy

Let's look at all of these at once: I want a breakdown of the most common manners of death for **men**, based on race.

Percentages, please, not raw numbers.

You can look at women, too, although I think the numbers are more surprising for men.

## Back to drugs: what is the most popular opioid-related primary cause of death that does NOT involve fentanyl?

- *Tip: Pay attention to your column names! There's one that might tell you if something is opioid-related...*
- *Tip: Usually you can use `not` or `!` to means "not", but for pandas and `.isin` or `.str.contains` you need to use `~`*
- *Tip: For "and" in pandas you'll need to use `&`, and make sure all of your clauses have parens around them, e.g. `df[(df.col1 = 'A') & (df.col2 = 'B')]`.*

# How do heroin and fentanyl deaths compare?

## Count the number of deaths involving heroin, the number of deaths involving fentanyl, and the number of deaths involving both.

- *Tip: This will take 3 different statements*
- *Tip: You should get `813` that include both*

## That's weird.

I heard fentanyl really surpassed heroin in the past few years. Let's see how this 

### Pull the year out and store it in a new column called `year`

If you run `df['Date of Incident'].str.extract("(\d\d\d\d)", expand=False)`, it will pull out the year of each incident. **Store this in a new column called `year`.**

(It's regular expression stuff. `\d\d\d\d` means "four numbers in a row", and `()` + `.str.extract` means "pull it out".)

### What is the datatype of the new `year` column?

## Convert this new column to an integer and save it back on top of itself

- *Tip: This uses is your friend `.astype`*
- *Tip: Make sure to save it back on top of itself!*

## Confirm the column is a number

## Plot the number of opioid deaths by year

If you'd like to make it look nicer, do some sorting and get rid of 2018.

- *Tip: Think of it in a few steps. First, filter for opioid deaths. Then get the number of deaths for each year. Then plot it.*
- *Tip: What's up with 2018? Why's it look so weird? Can you get rid of it? Remember to use lots of parens!*
- *Tip: Make sure the earliest year is on the left. You might need to sort by something other than values.*

## Plot the number of fentanyl deaths by year, and the number of heroin deaths by year

- *Tip: You'll want to look up how to use `ylim` - it will let you set each graphic to use the same scale. This should be separate graphics.*
- *Tip: Pay attention to the numbers on your axes. `sort_index()` will be your friend.*
- *Tip: You should probably get rid of 2018*

## How does this compare to gun deaths?

## But hey: numbers can lie pretty easily!

The numbers are just so low in 2014 and much higher in 2017. What's going on there?

Well, maybe **there just isn't as much data from the earlier years**. Plot how many entries there are for each year.

And we don't know the best way to fix that up yet, so instead I'm going to give you a present.

# Is the true lesson here, don't move to Cook County, Illinois?

Cook County is basically Chicago. It's probably just certain areas that are trouble, right? Let's investigate that without even having a clue how mapping works.

## Fun bonus: Making cheating maps

### Make a new dataframe of every death in the actual city of Chicago

### Confirm this new dataframe has 13,627 rows

### Use lat and long in the worst way possible to make a map

Use `longitude` and `latitude` and `plot` to make a rough map of the city. Chicago [looks like this](https://en.wikipedia.org/wiki/File:DuPage_County_Illinois_Incorporated_and_Unincorporated_areas_Chicago_Highlighted.svg)

- *Tip: Use the `latitude` and `longitude` columns*
- *Tip: You don't want a line graph, of course. Or a bar. What kind is the kind with dots on it?*
- *Tip: Use something like like `figsize=(10,5)` to specify the height and width of the map (but, you know, with better numbers that make it look like chicago)*

## Now let's find out where to live

Make a map of every non-homicide death in Chicago, then plot the homicides on top of it.

Use the `ax=df.plot` trick from the beer cans assignment to plot all of the rows representing homicides vs non-homicides. You can use `color='red'` to make one of them red, and `alpha=0.05` to make each mark very transparent to allow them to layer on top of each other.

## Never tell anyone I let you do that.

But you want to see something actually completely legitimately insane?

**Chicago is one of the most segregated cities in America.** If you'd like to see this for yourself, make a map of `Race`. Plot black vs white in a way similar to what we did above.

Yup.